import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'da';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.companies': 'For Companies',
    'nav.bugBounty': 'Bug Bounty Platform',
    'nav.compliance': 'Compliance',
    'nav.communityFund': 'Community Fund',
    'nav.about': 'About',
    
    // Hero Section
    'hero.title': 'A safer digital',
    'hero.titleAccent': 'Denmark',
    'hero.subtitle': 'Defend Denmark is a progressive cyber security company specialising in proactive security measures. We have the country\'s leading ethical hackers which simulate the methods of hackers and thus find security vulnerabilities in software systems of companies and organisations.',
    'hero.bookDemo': 'Book a Demo',
    'hero.learnMore': 'Learn More',
    
    // Preventive Measures
    'preventive.title': 'Preventive measures',
    'preventive.description': 'Our ethical hackers simulate real attacks and find new vulnerabilities in the custom-built software infrastructures that our customers use. By proactively identifying and addressing these issues, we help our customers strengthen their overall security posture and reduce the risk of cyber threats.',
    
    // Bug Bounty Page
    'bugBounty.hero.title': 'Proactive cybersecurity',
    'bugBounty.hero.subtitle': 'Strengthen your digital posture with the best Danish ethical hackers',
    'bugBounty.what.title': 'What is a bug bounty platform?',
    'bugBounty.what.desc1': 'A bug bounty platform is a service that connects organizations with ethical hackers to identify and fix security vulnerabilities in their systems. Organizations create programs offering rewards for discovering and reporting specific types of bugs, such as vulnerabilities in software, websites, or applications. Ethical hackers participate by testing the systems within the agreed-upon scope, providing detailed reports of their findings. The platform facilitates secure communication, manages submissions, and ensures payments are made to defenders who contribute valuable discoveries. This model helps organizations enhance their cyber security posture cost-effectively by leveraging a network of experts.',
    'bugBounty.what.desc2': 'Defend Denmark is a unique, nationwide bug bounty platform that aims to accelerate bug bounty uptake for SMEs and governmental institutions in Denmark by providing an innovative bug bounty platform that eliminates common barriers that have so far prevented rapid uptake of such solutions.',

    // Bug Bounty Concept
    'concept.badge': 'Bug Bounty Programs',
    'concept.title': 'What is a Bug Bounty?',
    'concept.subtitle': 'Bug bounty programs are crowdsourced cybersecurity initiatives where organizations invite ethical hackers to find and report security vulnerabilities in exchange for rewards. This collaborative approach helps identify weaknesses before they can be exploited by malicious actors.',
    'concept.feature1.title': 'Vulnerability Discovery',
    'concept.feature1.desc': 'Security researchers find and report vulnerabilities in your systems before malicious actors can exploit them.',
    'concept.feature2.title': 'Continuous Security',
    'concept.feature2.desc': 'Instead of yearly audits, utilize the power of a large Danish community of ethical hackers to continuously address your systems.',
    'concept.feature3.title': 'Collaborative Defense',
    'concept.feature3.desc': 'Defend Denmark together with the ethical hackers and yourself, helps pinpoint the details about your security posture.',
    'concept.feature4.title': 'Reward System',
    'concept.feature4.desc': 'Fair compensation for researchers who help improve your security posture through responsible disclosure.',
    'concept.why.title': 'Why Choose Bug Bounty Programs?',
    'concept.why.benefit1': 'Cost-effective security testing with pay-per-vulnerability model',
    'concept.why.benefit2': 'Access to diverse expertise from the Danish security community',
    'concept.why.benefit3': 'Continuous security monitoring beyond traditional penetration testing',
    'concept.why.benefit4': 'Enhanced reputation through transparent security practices',
    'concept.why.tagline': 'Strengthen your security posture with the power of the crowd',

    // Bug Bounty Steps
    'steps.badge': 'How It Works',
    'steps.title': 'Bug Bounty Process',
    'steps.subtitle': 'Our comprehensive 8-step approach ensures thorough security testing and responsible vulnerability management for Danish organizations.',
    'steps.1.title': 'Activate Elite Talent',
    'steps.1.desc': 'We engage Denmark\'s most skilled cybersecurity professionals to strengthen your digital defenses.',
    'steps.2.title': 'Launch Security Testing',
    'steps.2.desc': 'Our platform deployment is seamless, and vulnerability discovery begins immediately.',
    'steps.3.title': 'Simulate Real Attacks',
    'steps.3.desc': 'Security experts replicate actual threat actor methodologies against your systems.',
    'steps.4.title': 'Validate Vulnerabilities',
    'steps.4.desc': 'Our team verifies each finding, assesses severity, and prioritizes remediation efforts.',
    'steps.5.title': 'Deliver Actionable Intelligence',
    'steps.5.desc': 'Receive detailed technical documentation and practical remediation guidance.',
    'steps.6.title': 'Reward Discoveries',
    'steps.6.desc': 'Compensate security researchers for validated vulnerabilities through our transparent bounty system.',
    'steps.7.title': 'Contribute to Community',
    'steps.7.desc': 'A percentage of each bounty payment supports Denmark\'s broader cybersecurity ecosystem - The community fund.',
    'steps.8.title': 'Responsible Disclosure',
    'steps.8.desc': 'Defend Denmark provides a secure channel for reporting vulnerabilities, creating a safer digital environment.',
    
    // Community Fund
    'fund.hero.title': 'Community Fund',
    'fund.hero.subtitle': 'Strengthening Denmark\'s cybersecurity through community-driven innovation and support',
    'fund.badge': 'Community Impact',
    'fund.title': 'Denmark Community Fund',
    'fund.subtitle': 'Cyber security for everyone',
    'fund.intro.desc1': 'Our bug bounty platform is unique in that it is community driven. With a fund that is financed by companies that invest in their own security, but who, by increasing their own security, also want to contribute to protecting Denmark. At the same time, the fund is designed to benefit, for example, charities, start-ups and public institutions with limited resources.',
    'fund.intro.desc2': 'The fund is based on the social responsibility of those organizations and companies that have the budget to finance their own bug bounty platform and show a willingness to help finance a system designed for the community as a whole.',
    'fund.intro.desc3': 'The community fund is designed for those who don\'t have the financial means, and at the same time is a way to encourage the defenders to report all incidents of security vulnerabilities in our community, no matter who is affected.',
    'fund.activate.title': 'Let\'s activate expertise',
    'fund.activate.desc1': 'With the community fund, we create an incentive system where the expertise and skills of ethical hackers are activated to benefit the community. Rewards are paid from the fund for security vulnerabilities that are reported to Defend Denmark, at companies or institutions that do not have the funds to pay rewards.',
    'fund.activate.desc2': 'With this, we approach Denmark\'s cyber security in a holistic way, but Defend Denmark\'s future vision is that all companies and institutions in Denmark can use the bug bounty platform to increase their cyber security.',
    'fund.structure.title': 'Structure of the fund',
    'fund.structure.desc1': 'The community fund is financed on the one hand by Defend Denmark\'s customers and on the other hand by the community of ethical hackers.',
    'fund.structure.desc2': 'The customer\'s contribution is based on the paid reward money for security vulnerabilities, but on top of those payments a 10% flat fee is added, which is the customer\'s contribution to the fund every time they pay for a vulnerability. The community fund therefore grows with each security vulnerability found.',
    'fund.structure.desc3': 'Ethical hackers can also make voluntary contributions to the fund from their own reward money.',
    'fund.structure.desc4': 'The reward money paid out of the fund takes into account its status at any given time and the potential impact of the vulnerabilities on Denmark\'s digital community.',
    'fund.collab.title': 'Collaborative Security',
    'fund.collab.desc': 'Companies and security experts contribute together to strengthen Denmark\'s overall cybersecurity posture.',
    'fund.nonprofit.title': 'Non-Profit Support',
    'fund.nonprofit.desc': 'Fund security assessments for organizations protecting sensitive citizen data and critical services.',
    'fund.impact.title': 'Growing Impact',
    'fund.impact.desc': 'As more organizations join, the fund grows to support an expanding network of digital security initiatives.',
    'fund.fundTitle': 'Community Fund',
    'fund.fundDesc': 'Building resources to protect Denmark\'s digital infrastructure',
    'fund.companyContrib': 'Company Contributions',
    'fund.expertContrib': 'Expert Contributions',
    'fund.prelaunch': 'Current balance',
    'fund.launchText': 'The fund grows with every vulnerability found. Companies contribute 10% on top of each bounty payment.',
    
    // Footer
    'footer.tagline': 'Securing Denmark\'s digital future through collaborative cybersecurity excellence.',
    'footer.platform': 'Platform',
    'footer.community': 'Community',
    'footer.communityFund': 'Community Fund',
    'footer.company': 'Company',
    'footer.companyName': 'Defend Denmark ApS',
    'footer.address1': 'Nørrebrogade 45D 4TH',
    'footer.address2': '2200 København N, DK',
    'footer.about': 'About',
    'footer.forResearchers': 'For Security Researchers',
    'footer.forCompanies': 'For Companies',
    'footer.copyright': '© 2025 Defend Denmark. All rights reserved.',
    'footer.prelaunch.title': 'Sign up for Defend Denmark',
    'footer.prelaunch.description': 'Whether you are a security researcher or a company who wishes to work with ethical hackers, we are eager to welcome you on the platform. Please fill out the form and we will get back to you as soon as possible.',
    'footer.prelaunch.button': 'Sign up',

    // Compliance Hub
    'compliance.hub.title': 'Bug Bounty for Compliance',
    'compliance.hub.subtitle': 'Continuous, evidence-driven security testing that maps to EU cybersecurity regulation — DORA, NIS2, and the Cyber Resilience Act.',
    'compliance.hub.intro': 'Modern EU cybersecurity rules expect ongoing vulnerability management, coordinated disclosure, and documented evidence. Defend Denmark provides crowdsourced security testing that produces exactly that — continuous coverage, classified findings, and audit-ready reports for your supervisory authority.',
    'compliance.hub.frameworks.title': 'Choose your framework',
    'compliance.hub.frameworks.subtitle': 'Each framework has its own page with article-by-article mapping of how our service satisfies the requirement and the evidence we deliver.',

    'compliance.hub.dora.title': 'DORA',
    'compliance.hub.dora.full': 'Digital Operational Resilience Act',
    'compliance.hub.dora.summary': 'EU regulation in force since January 2025. Mandates annual digital operational resilience testing for financial entities. We satisfy Articles 24-25 through continuous testing and prepare you for TLPT.',
    'compliance.hub.dora.cta': 'See DORA coverage',

    'compliance.hub.nis2.title': 'NIS2',
    'compliance.hub.nis2.full': 'NIS2 Directive',
    'compliance.hub.nis2.summary': 'Transposed into Danish law as NIS2-loven, covering 18 sectors of essential and important entities. We deliver Article 21 evidence of effective vulnerability handling and Article 12 coordinated disclosure.',
    'compliance.hub.nis2.cta': 'See NIS2 coverage',

    'compliance.hub.cra.title': 'CRA',
    'compliance.hub.cra.full': 'Cyber Resilience Act',
    'compliance.hub.cra.summary': 'EU regulation for products with digital elements. Main obligations from December 2027. We establish the Article 13 coordinated vulnerability disclosure policy and feed the conformity assessment evidence trail.',
    'compliance.hub.cra.cta': 'See CRA coverage',

    'compliance.hub.cta.title': 'Not sure which framework applies to you?',
    'compliance.hub.cta.subtitle': 'Book a 30-minute consultation. We will map your obligations against what we deliver.',
    'compliance.hub.cta.button': 'Book a consultation',

    // Compliance — shared section labels
    'compliance.section.requires': 'What the regulation requires',
    'compliance.section.fits': 'How our service satisfies each article',
    'compliance.section.evidence': 'Evidence and reporting we deliver',
    'compliance.section.local': 'Local context',
    'compliance.coverage.col.article': 'Article reference',
    'compliance.coverage.col.deliverable': 'How Defend Denmark satisfies it',
    'compliance.cta.download': 'Download the example compliance report',
    'compliance.cta.book': 'Book a consultation',
    'compliance.cta.note': 'PDFs — example artifacts a Defend Denmark customer receives, plus the agreement every researcher signs',
    'compliance.cta.examples': 'See example vulnerability reports',
    'compliance.cta.examples.label': 'Pick a vulnerability class',
    'compliance.cta.examples.idor': 'IDOR — Insecure Direct Object Reference',
    'compliance.cta.examples.bxss': 'Blind XSS',
    'compliance.cta.examples.rce': 'Remote Code Execution',
    'compliance.cta.agreement': 'See the Defenders Agreement',

    // DORA page
    'compliance.dora.seo.title': 'DORA Compliance with Bug Bounty | Defend Denmark',
    'compliance.dora.seo.description': 'How Defend Denmark satisfies DORA Articles 24, 25, and 45 through continuous, crowdsourced security testing for EU financial entities. Article-by-article mapping of deliverables.',
    'compliance.dora.hero.title': 'DORA',
    'compliance.dora.hero.subtitle': 'Continuous, evidence-driven security testing that maps directly to DORA Articles 24, 25, and 45 — and prepares you for Threat-Led Penetration Testing under Article 26.',
    'compliance.dora.what.title': 'What is DORA?',
    'compliance.dora.what.body': 'DORA is the EU regulation on digital operational resilience for the financial sector. It has been in force since 17 January 2025 and applies to banks, insurers, investment firms, payment institutions, crypto-asset service providers, and the critical ICT third-party providers that serve them.',

    'compliance.dora.req.intro': 'DORA Chapters II and IV impose specific testing and vulnerability-management duties on financial entities. The articles most relevant to ongoing security testing are:',
    'compliance.dora.req.1.article': 'Article 6',
    'compliance.dora.req.1.title': 'ICT risk management framework',
    'compliance.dora.req.1.body': 'Financial entities must establish a sound, comprehensive and well-documented ICT risk management framework covering identification, protection, detection, response, and recovery.',
    'compliance.dora.req.2.article': 'Article 24',
    'compliance.dora.req.2.title': 'General requirements for digital operational resilience testing',
    'compliance.dora.req.2.body': 'Establishes a sound, comprehensive digital operational resilience testing programme as an integral part of the ICT risk management framework, with risk-based methodologies and full documentation.',
    'compliance.dora.req.3.article': 'Article 25',
    'compliance.dora.req.3.title': 'Testing of ICT tools and systems',
    'compliance.dora.req.3.body': 'Tests of ICT tools and systems must include vulnerability assessments and scans, open-source analyses, network security assessments, gap analyses, physical security reviews, source code reviews, scenario-based tests, compatibility testing, performance testing, end-to-end testing, and penetration testing — appropriate to risk.',
    'compliance.dora.req.4.article': 'Article 26-27',
    'compliance.dora.req.4.title': 'Advanced testing — Threat-Led Penetration Testing (TLPT)',
    'compliance.dora.req.4.body': 'Designated entities carry out TLPT at least every three years, following the TIBER-EU framework, executed by qualified internal or external testers meeting Article 27 requirements.',
    'compliance.dora.req.5.article': 'Article 45',
    'compliance.dora.req.5.title': 'Information-sharing arrangements on cyber threat information',
    'compliance.dora.req.5.body': 'Financial entities may exchange cyber threat information and intelligence — including indicators of compromise and tactics — within trusted communities to enhance digital operational resilience.',
    'compliance.dora.req.6.article': 'Article 13',
    'compliance.dora.req.6.title': 'Learning and evolving',
    'compliance.dora.req.6.body': 'Entities must monitor the effectiveness of their digital operational resilience strategy, capture lessons from tests and incidents, and feed them back into the ICT risk management framework.',

    'compliance.dora.coverage.intro': 'Each Defend Denmark deliverable below maps directly to a DORA article. Our reports are structured so you can hand them to Finanstilsynet and point at the specific obligation each artefact satisfies.',
    'compliance.dora.coverage.1.article': 'Article 6 — ICT risk management framework',
    'compliance.dora.coverage.1.how': 'Continuous crowdsourced testing produces ongoing identification, detection, and response evidence across all in-scope ICT systems. Findings are classified by severity, asset, and CWE so they slot directly into your risk register.',
    'compliance.dora.coverage.2.article': 'Article 24 — Resilience testing programme',
    'compliance.dora.coverage.2.how': 'Defend Denmark functions as a documented testing programme: scope, methodology, frequency, and risk-prioritised coverage are captured in writing. Annual programme summaries are produced for regulator review.',
    'compliance.dora.coverage.3.article': 'Article 25 — Testing of ICT tools and systems',
    'compliance.dora.coverage.3.how': 'We deliver the testing methodologies named in Article 25 in a continuous form: vulnerability assessments, scans, network security assessments, source code reviews (where in scope), scenario-based tests, and penetration testing — performed by verified ethical hackers across the year, not as a one-off audit.',
    'compliance.dora.coverage.4.article': 'Article 26 — Preparing for TLPT',
    'compliance.dora.coverage.4.how': 'For designated entities subject to TLPT, our continuous coverage hardens assets and surfaces issues before the threat-led engagement begins. We do not replace TLPT (which requires Article 27 testers); we reduce its findings and improve its outcome.',
    'compliance.dora.coverage.5.article': 'Article 45 — Cyber threat information sharing',
    'compliance.dora.coverage.5.how': 'Our coordinated vulnerability disclosure channel between researchers and your security team is itself an Article 45 information-sharing arrangement. Findings, indicators, and remediation guidance flow into your trusted-community processes.',
    'compliance.dora.coverage.6.article': 'Article 13 — Learning and evolving',
    'compliance.dora.coverage.6.how': 'Periodic executive summaries — MTTR by severity, finding density, CWE distribution, retest outcomes — give you the lessons-learned input that Article 13 expects, ready to feed back into the ICT risk framework.',

    'compliance.dora.evidence.1': 'Per-finding reports with CVSS-based severity, reproduction steps, affected assets, and remediation guidance.',
    'compliance.dora.evidence.2': 'Triage timestamps and SLA evidence demonstrating continuous coverage across the testing year.',
    'compliance.dora.evidence.3': 'Remediation tracking and re-test validation per Article 24(5) internal validation expectations.',
    'compliance.dora.evidence.4': 'Annual digital operational resilience testing programme summary aligned with Article 24.',
    'compliance.dora.evidence.5': 'Periodic executive attestations suitable for board reporting and supervisory dialogue.',
    'compliance.dora.evidence.6': 'Aggregated metrics: coverage, MTTR, finding distribution by severity, asset class, and vulnerability type (CWE).',

    'compliance.dora.local.title': 'Denmark',
    'compliance.dora.local.body': 'In Denmark, DORA is supervised by Finanstilsynet (the Danish Financial Supervisory Authority), the competent authority responsible for ensuring that Danish financial entities comply with the regulation. Our reporting is structured to be directly usable in supervisory dialogue with Finanstilsynet.',

    // NIS2 page
    'compliance.nis2.seo.title': 'NIS2 Compliance with Vulnerability Disclosure | Defend Denmark',
    'compliance.nis2.seo.description': 'Defend Denmark delivers Article 21(2)(e) vulnerability handling, Article 21(2)(f) effectiveness assessment, and Article 12 coordinated disclosure for essential and important entities under NIS2 / NIS2-loven.',
    'compliance.nis2.hero.title': 'NIS2',
    'compliance.nis2.hero.subtitle': 'Article-by-article coverage of vulnerability handling, coordinated disclosure, and effectiveness assessment for essential and important entities across all 18 covered sectors.',
    'compliance.nis2.what.title': 'What is NIS2?',
    'compliance.nis2.what.body': 'NIS2 is the EU directive that significantly expands cybersecurity obligations across the union. It is transposed into Danish law as NIS2-loven and reaches "essential" and "important" entities in 18 sectors — including energy, transport, healthcare, digital infrastructure, public administration, manufacturing, and food.',

    'compliance.nis2.req.intro': 'NIS2 places concrete cybersecurity, vulnerability-handling, and disclosure duties on essential and important entities. The articles most relevant to ongoing security testing are:',
    'compliance.nis2.req.1.article': 'Article 12',
    'compliance.nis2.req.1.title': 'Coordinated vulnerability disclosure and a European vulnerability database',
    'compliance.nis2.req.1.body': 'Member States designate a CSIRT as coordinator for coordinated vulnerability disclosure. ENISA operates a European vulnerability database to enable Union-wide sharing of vulnerability information.',
    'compliance.nis2.req.2.article': 'Article 21(1)',
    'compliance.nis2.req.2.title': 'Cybersecurity risk-management measures',
    'compliance.nis2.req.2.body': 'Essential and important entities must take appropriate and proportionate technical, operational, and organisational measures to manage the risks posed to the security of network and information systems.',
    'compliance.nis2.req.3.article': 'Article 21(2)(b)',
    'compliance.nis2.req.3.title': 'Incident handling',
    'compliance.nis2.req.3.body': 'Entities must put in place documented processes for incident handling, including detection, analysis, containment, and response.',
    'compliance.nis2.req.4.article': 'Article 21(2)(e)',
    'compliance.nis2.req.4.title': 'Security in network and information systems acquisition, development and maintenance — including vulnerability handling and disclosure',
    'compliance.nis2.req.4.body': 'Entities must operate processes for vulnerability handling and disclosure as part of securing the systems they acquire, develop, and maintain.',
    'compliance.nis2.req.5.article': 'Article 21(2)(f)',
    'compliance.nis2.req.5.title': 'Policies and procedures to assess effectiveness of cybersecurity risk-management measures',
    'compliance.nis2.req.5.body': 'Entities must adopt policies and procedures — for example, regular testing — to assess the effectiveness of their cybersecurity risk-management measures.',
    'compliance.nis2.req.6.article': 'Article 23',
    'compliance.nis2.req.6.title': 'Reporting obligations',
    'compliance.nis2.req.6.body': 'Significant incidents must be notified to the CSIRT or competent authority — early warning within 24 hours, incident notification within 72 hours, and a final report within one month.',

    'compliance.nis2.coverage.intro': 'Each Defend Denmark deliverable below maps directly to a NIS2 article. Our reports are designed to be presentable as evidence to a Danish supervisor — point at the relevant article, hand over the artefact.',
    'compliance.nis2.coverage.1.article': 'Article 12 — Coordinated vulnerability disclosure',
    'compliance.nis2.coverage.1.how': 'Defend Denmark operates as your coordinated vulnerability disclosure (CVD) intake — verified researchers submit, we triage, you receive structured reports. The programme is aligned with the Member State CVD policy and feeds the ENISA European vulnerability database where applicable.',
    'compliance.nis2.coverage.2.article': 'Article 21(2)(e) — Vulnerability handling and disclosure',
    'compliance.nis2.coverage.2.how': 'A documented, audit-ready vulnerability handling programme: researcher submission, classification, severity scoring, remediation tracking, and retest validation. The programme itself is the evidence Article 21(2)(e) asks for.',
    'compliance.nis2.coverage.3.article': 'Article 21(2)(f) — Effectiveness assessment',
    'compliance.nis2.coverage.3.how': 'Continuous testing produces effectiveness metrics — MTTR by severity, finding density over time, retest pass-rate, coverage breadth. These are exactly the "policies and procedures to assess effectiveness" the article requires.',
    'compliance.nis2.coverage.4.article': 'Article 21(2)(b) — Incident handling input',
    'compliance.nis2.coverage.4.how': 'Per-finding reports include reproduction steps, severity, and discovery timestamps — directly usable as input to your incident handling process when a finding crosses the significance threshold.',
    'compliance.nis2.coverage.5.article': 'Article 23 — Notification timeline support',
    'compliance.nis2.coverage.5.how': 'Findings reach you with timestamps that support the 24h early warning and 72h incident notification timelines. Notification to the CSIRT remains your responsibility; the time-to-discovery evidence is in our reports.',
    'compliance.nis2.coverage.6.article': 'Article 21(1) — Risk-management measures',
    'compliance.nis2.coverage.6.how': 'Coverage reports demonstrate that the technical measure of continuous third-party testing has been adopted in proportion to the risk profile of your network and information systems.',

    'compliance.nis2.evidence.1': 'Documented Coordinated Vulnerability Disclosure (CVD) policy aligned with Article 12.',
    'compliance.nis2.evidence.2': 'Per-finding reports with severity classification, reproduction steps, and remediation tracking.',
    'compliance.nis2.evidence.3': 'Effectiveness metrics — MTTR by severity, retest pass-rate, finding density — for Article 21(2)(f) reporting.',
    'compliance.nis2.evidence.4': 'Annual programme summary suitable for handover to the competent authority or sectoral supervisor.',
    'compliance.nis2.evidence.5': 'Discovery timestamps and chain-of-evidence supporting Article 23 notification timelines.',

    'compliance.nis2.local.title': 'Denmark',
    'compliance.nis2.local.body': 'In Denmark, NIS2-loven is supervised by Digitaliseringsstyrelsen within the digital sector in Denmark. Our disclosure programme and audit-ready reports are designed to slot into the documentation a Danish supervisor expects to see.',

    // CRA page
    'compliance.cra.seo.title': 'Cyber Resilience Act Compliance | Defend Denmark',
    'compliance.cra.seo.description': 'Defend Denmark satisfies CRA Article 13 manufacturer obligations and Annex I Part II vulnerability handling requirements through continuous discovery, CVD policy operation, and conformity-assessment-ready documentation.',
    'compliance.cra.hero.title': 'CRA',
    'compliance.cra.hero.subtitle': 'Article-by-article coverage of manufacturer obligations and Annex I vulnerability handling for any product with digital elements sold in the EU.',
    'compliance.cra.what.title': 'What is the Cyber Resilience Act?',
    'compliance.cra.what.body': 'The CRA is the EU regulation that entered into force in December 2024, with main obligations applying from December 2027. It covers any product with digital elements sold in the EU — IoT devices, software, hardware with connectivity — and applies to manufacturers, importers, and distributors.',

    'compliance.cra.req.intro': 'CRA combines essential cybersecurity requirements (Annex I) with manufacturer duties (Article 13), reporting obligations (Article 14), and a documentation regime (Article 31) that feeds the conformity assessment route to CE marking. The articles most relevant to ongoing security testing are:',
    'compliance.cra.req.1.article': 'Article 6 + Annex I Part I',
    'compliance.cra.req.1.title': 'Essential cybersecurity requirements for products with digital elements',
    'compliance.cra.req.1.body': 'Products must be designed, developed, and produced to ensure an appropriate level of cybersecurity based on risks — including being delivered without known exploitable vulnerabilities and protected from unauthorised access.',
    'compliance.cra.req.2.article': 'Article 13',
    'compliance.cra.req.2.title': 'Obligations of manufacturers',
    'compliance.cra.req.2.body': 'Manufacturers must operate vulnerability handling processes throughout the support period, including a coordinated vulnerability disclosure policy and a single point of contact for reporting vulnerabilities.',
    'compliance.cra.req.3.article': 'Annex I Part II',
    'compliance.cra.req.3.title': 'Vulnerability handling requirements',
    'compliance.cra.req.3.body': 'Identify and document vulnerabilities; address them without delay through security updates; perform regular tests and reviews; share information about fixed vulnerabilities; operate a coordinated vulnerability disclosure policy.',
    'compliance.cra.req.4.article': 'Article 14',
    'compliance.cra.req.4.title': 'Reporting obligations of manufacturers',
    'compliance.cra.req.4.body': 'Actively exploited vulnerabilities and severe incidents must be reported to ENISA — early warning within 24 hours, full notification within 72 hours, and final report within 14 days.',
    'compliance.cra.req.5.article': 'Article 31',
    'compliance.cra.req.5.title': 'Technical documentation',
    'compliance.cra.req.5.body': 'Manufacturers must draw up and keep technical documentation demonstrating conformity with the essential requirements — including the cybersecurity risk assessment and the vulnerability handling processes.',
    'compliance.cra.req.6.article': 'Article 32',
    'compliance.cra.req.6.title': 'Conformity assessment procedures',
    'compliance.cra.req.6.body': 'Before placing a product on the market, manufacturers carry out a conformity assessment to demonstrate fulfilment of the essential requirements — the route depending on whether the product is default, important, or critical.',

    'compliance.cra.coverage.intro': 'Each Defend Denmark deliverable below maps directly to a CRA article or Annex I requirement. Our outputs are produced in a form that goes straight into your technical documentation file and conformity assessment.',
    'compliance.cra.coverage.1.article': 'Article 13 + Annex I Part II.5 — Coordinated vulnerability disclosure policy',
    'compliance.cra.coverage.1.how': 'Defend Denmark provides the documented CVD policy and operates the single point of contact for reporting vulnerabilities. Researcher submissions are received, triaged, and tracked under your name — directly satisfying the manufacturer obligation.',
    'compliance.cra.coverage.2.article': 'Annex I Part II.1 — Identify and document vulnerabilities',
    'compliance.cra.coverage.2.how': 'Continuous external vulnerability discovery by verified ethical hackers throughout the product support period. Each finding is documented with affected component, version, severity, and reproduction steps.',
    'compliance.cra.coverage.3.article': 'Annex I Part II.2 — Address without delay',
    'compliance.cra.coverage.3.how': 'Per-finding reports include exploitability assessment and concrete remediation guidance, enabling your engineering team to issue timely security updates within the support period.',
    'compliance.cra.coverage.4.article': 'Annex I Part II.3 — Regular tests and reviews',
    'compliance.cra.coverage.4.how': 'The Defend Denmark programme is itself an ongoing test-and-review regime — broader than periodic pentests and proportionate to the risk profile of the product. Coverage reports demonstrate the regularity.',
    'compliance.cra.coverage.5.article': 'Annex I Part II.6 — Information sharing about vulnerabilities',
    'compliance.cra.coverage.5.how': 'Aggregated and per-finding reporting feeds your information-sharing obligations and supports the customer-facing communication of fixed vulnerabilities.',
    'compliance.cra.coverage.6.article': 'Article 14 — 24h ENISA reporting timeline',
    'compliance.cra.coverage.6.how': 'Severity-classified, time-stamped findings give you the early-warning signal needed to meet the 24h ENISA notification window for actively exploited issues. Notification itself remains the manufacturer\'s act; we provide the discovery evidence and timeline.',
    'compliance.cra.coverage.7.article': 'Article 31 — Technical documentation',
    'compliance.cra.coverage.7.how': 'Per-finding reports, remediation evidence, retest validation, and the CVD policy documentation are produced in a form that goes straight into the technical documentation file.',
    'compliance.cra.coverage.8.article': 'Article 32 — Conformity assessment',
    'compliance.cra.coverage.8.how': 'Programme summaries and coverage reports are usable as evidence of effective vulnerability handling within the conformity assessment route — whether internal control (default) or third-party assessment (important / critical).',

    'compliance.cra.evidence.1': 'Documented Coordinated Vulnerability Disclosure (CVD) policy meeting Article 13 and Annex I Part II.5.',
    'compliance.cra.evidence.2': 'Single point of contact for vulnerability reporting, operated by Defend Denmark on the manufacturer\'s behalf.',
    'compliance.cra.evidence.3': 'Per-finding reports — affected component, severity, reproduction steps, remediation guidance, retest evidence.',
    'compliance.cra.evidence.4': 'Continuous coverage reporting suitable as input to the Article 31 technical documentation file.',
    'compliance.cra.evidence.5': 'Time-stamped discovery evidence supporting the Article 14 24h / 72h / 14-day ENISA reporting timeline.',
    'compliance.cra.evidence.6': 'Programme summaries usable in the Article 32 conformity assessment route.',

    'compliance.cra.local.title': 'Denmark',
    'compliance.cra.local.body': 'In Denmark, supervision and market surveillance under the Cyber Resilience Act is carried out by Styrelsen for Samfundssikkerhed (Samsik) — the Danish Authority for Societal Security — which is responsible for auditing manufacturers\' compliance with the regulation. Our disclosure programme is structured to plug directly into a Danish manufacturer\'s technical documentation and post-market vulnerability handling, ready for Samsik review.',

    // Companies Page
    'companies.title': 'For Companies',
    'companies.subtitle': 'Strengthen your IT security with Danish freelance ethical hackers',
    'companies.howItWorks': 'How it works for you',
    'companies.step1.title': 'Set up program',
    'companies.step1.desc': 'Define what you want tested, your rules and rewards for your bug bounty program',
    'companies.step2.title': 'Danish hackers test',
    'companies.step2.desc': 'Verified ethical hackers begin testing your systems for vulnerabilities',
    'companies.step3.title': 'Receive reports',
    'companies.step3.desc': 'We verify and investigate all vulnerability reports from the hackers',
    'companies.step4.title': 'Approve & pay',
    'companies.step4.desc': 'You only pay for real and impactful vulnerabilities that are found',
    'companies.benefit1.title': 'Continuous security testing',
    'companies.benefit1.desc': 'Get your systems tested continuously by ethical hackers',
    'companies.benefit2.title': 'Cost-effective',
    'companies.benefit2.desc': 'Pay only for real vulnerabilities found - lower than consultant costs',
    'companies.benefit3.title': 'Verified ethical hackers',
    'companies.benefit3.desc': 'All ethical hackers are MitID verified and agree to our ethical guidelines',
    'companies.benefit4.title': 'Professional verification',
    'companies.benefit4.desc': 'Our own security experts verify, triage and prioritize all reported vulnerabilities',
    'companies.benefit5.title': 'Fast response',
    'companies.benefit5.desc': 'Critical vulnerabilities are reported within 24 hours',
    'companies.benefit6.title': 'Dedicated support',
    'companies.benefit6.desc': 'Danish customer service, guidance and technical support throughout the process',

    // About Page
    'about.hero.title': 'About Defend Denmark',
    'about.hero.subtitle': 'A secure digital future for Denmark through innovative cybersecurity and ethical hacking',
    'about.prelaunch.title': 'Now Live',
    'about.prelaunch.description': 'Defend Denmark is officially launched and operational. We are actively onboarding both security researchers and companies — reach out if you want to get started with your bug bounty program or join as an ethical hacker.',
    'about.hackers.title': 'Ready Security Researchers',
    'about.hackers.description': 'We have assembled a talented community of ethical hackers who are passionate about cybersecurity and ready to help Danish companies identify and fix security vulnerabilities. Our researchers undergo thorough vetting to ensure the highest standards of professionalism and integrity.',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'To become Denmark\'s leading cybersecurity platform, fostering a culture of proactive security testing and helping businesses stay ahead of cyber threats through responsible disclosure and collaborative security research.',
    'about.researcher.experience': 'Years of Experience',
    'about.founder.quote': 'After identifying hundreds of vulnerabilities myself and working with the best Danish ethical hackers, I realized that there weren\'t many Danish companies on bug bounty platforms. This led me to launch Defend Denmark to help Danish companies work with the Danish security community to find real and impactful vulnerabilities in Danish companies',
    'about.discord.title': 'Join Our Community',
    'about.discord.description': 'Connect with fellow security researchers, stay updated on the latest programs, and participate in discussions about Danish cybersecurity.',
    'about.discord.button': 'Join us on Discord',

    // Researchers Page
    'nav.researchers': 'For Researchers',
    'researchers.title': 'For Security Researchers',
    'researchers.subtitle': 'Get rewarded for your hacking skills',
    'researchers.howToEarn': 'How to get rewarded',
    'researchers.step1.title': 'Sign up',
    'researchers.step1.desc': 'Create profile and get verified as a defender',
    'researchers.step2.title': 'Find bugs',
    'researchers.step2.desc': 'Test selected Danish companies\' systems and find vulnerabilities',
    'researchers.step3.title': 'Report',
    'researchers.step3.desc': 'Write a detailed report about the vulnerability',
    'researchers.step4.title': 'Verification',
    'researchers.step4.desc': 'We confirm the vulnerability and assess the severity',
    'researchers.step5.title': 'Get paid',
    'researchers.step5.desc': 'Receive reward based on the vulnerability\'s criticality',
    'researchers.benefit1.title': 'High rewards',
    'researchers.benefit1.desc': 'Competitive payouts based on vulnerability criticality',
    'researchers.benefit2.title': 'Danish companies',
    'researchers.benefit2.desc': 'Work with well-known Danish brands and companies',
    'researchers.benefit3.title': 'Fast verification',
    'researchers.benefit3.desc': 'Receive feedback on found vulnerability within 5 business days',
    'researchers.benefit4.title': 'Professional support',
    'researchers.benefit4.desc': 'Get help with reporting and communication with companies',
    'researchers.benefit5.title': 'Gamification',
    'researchers.benefit5.desc': 'Receive points and recognition for all vulnerabilities, even if they don\'t give payout',
    'researchers.benefit6.title': 'Legal protection',
    'researchers.benefit6.desc': 'Safe framework for ethical hacking under Danish laws',
    'researchers.requirements.title': 'Requirements',
    'researchers.requirements.citizen': 'Danish Citizen or Resident. MitID access is required',
    'researchers.requirements.agreement': 'Willing to accept the defenders agreement —',
    'researchers.requirements.agreement.link': 'view the agreement',
    'researchers.requirements.record': 'Clean criminal record',
    'researchers.requirements.disclosure': 'Committed to responsible disclosure',

    // Spotlight / Security Researchers Carousel
    'spotlight.title': 'Meet Our Security Researchers',
    'spotlight.subtitle': 'Talented ethical hackers ready to protect Danish companies',
    'spotlight.disclaimer': 'Note: The vulnerabilities described below are not necessarily findings in Defend Denmark\'s customers, but also, independent research or contract work, and are presented here to demonstrate the skills and expertise of ethical hackers.',
    'spotlight.mitidVerified': 'MitID Verified',
    'spotlight.agreementSigned': 'Agreement Signed',
    'spotlight.viewAgreement': 'View the Defenders Agreement',
    'spotlight.ndaSigned': 'NDA Signed',
    'spotlight.profession': 'Profession',
    'spotlight.specialization': 'Specialization',
    'spotlight.experience': 'years',
    'spotlight.discoveries': 'Recent Discoveries',
    'spotlight.reward': 'Reward:',
    'spotlight.industry': 'Industry:',
    'spotlight.cvss': 'CVSS:',
    'spotlight.acceptedAs': 'Accepted as:',

    // Fund additional keys
    'fund.howItWorks': 'How the Community Fund Works',
    'fund.flowchartDesc': 'The Community Fund creates a sustainable ecosystem where businesses contribute to cybersecurity for organizations that cannot afford it, supported by ethical hackers who help secure Denmark\'s digital infrastructure.',

    // Not Found Page
    'notFound.message': 'Oops! Page not found',
    'notFound.returnHome': 'Return to Home',

    // Common
  },
  da: {
    // Navigation
    'nav.companies': 'For Virksomheder',
    'nav.bugBounty': 'Bug Bounty Platform',
    'nav.compliance': 'Compliance',
    'nav.communityFund': 'Fællesskabsfonden',
    'nav.about': 'Om Os',
    
    // Hero Section
    'hero.title': 'Et sikrere digitalt',
    'hero.titleAccent': 'Danmark',
    'hero.subtitle': 'Styrk jeres digitale sikkerhed via Defend Denmarks bug bounty platform. Vi samarbejder med landets dygtigste etiske hackere, som simulerer ondsindede aktørers metoder. De finder sårbarheder i jeres systemer og i betaler kun for reelle og alvorlige sårbarheder.',
    'hero.bookDemo': 'Book en Demo',
    'hero.learnMore': 'Lær Mere',
    
    // Preventive Measures
    'preventive.title': 'Crowdsourced sikkerhed',
    'preventive.description': 'Vores etiske hackere simulerer ondsindede aktørers angreb og finder nye sårbarheder i de IT-systemer, som vores kunder bruger, drifter eller selv bygger. Ved proaktivt at identificere disse sårbarheder hjælper vi vores kunder med at styrke deres samlede sikkerhedsposition.',
    
    // Bug Bounty Page
    'bugBounty.hero.title': 'Proaktiv sikkerhed',
    'bugBounty.hero.subtitle': 'Styrk jeres digitale modstandsdygtighed med Danmarks førende etiske hackere',
    'bugBounty.what.title': 'Hvad er en bug bounty platform?',
    'bugBounty.what.desc1': 'En bug bounty platform er en tjeneste, der forbinder etiske hackere med organisationer for at identificere sårbarheder i deres IT-systemer. Organisationer kan vælge hvad de ønsker at eksponere for de etiske hackere, og tilbyder dusører (bounties) for identificering og rapportering af specifikke typer bugs, såsom sårbarheder i software, hjemmesider eller applikationer. De danske etiske hackere bruger deres færdigheder til at teste systemerne inden for det aftalte rammer og leverer detaljerede rapporter om de fejl som bryder sikkerheden hos organisationerne. Defend Denmark faciliterer sikker kommunikation, verificerer fund og sikrer, at betalinger foretages til de etiske hackere. Denne model hjælper organisationer med at forbedre deres cybersikkerhedspostur omkostningseffektivt ved at udnytte dette unikke netværk af eksperter.',
    'bugBounty.what.desc2': 'Defend Denmark er en unik, landsdækkende bug bounty platform, der ønsker at levere "crowdsourced" pentesting til større virksomheder, SMV\'er og statslige institutioner i Danmark. Dette gøres ved at levere en fælles platform, som forbinder de etiske hackere med disse organisationer.',

    // Bug Bounty Concept
    'concept.badge': 'Bug Bounty Programmer',
    'concept.title': 'Hvad er Bug Bounty?',
    'concept.subtitle': 'Bug bounty programmer er crowdsourcede intitiativer inden for cybersikkerhed, hvor organisationer inviterer etiske hackere til at finde og rapportere sårbarheder i IT-sikkerhed i bytte for dusører. Denne samarbejdstilgang hjælper organisationer med at identificere svagheder, før de kan udnyttes af ondsindede aktører, samtidig med at der udelukkende betales for reelle sårbarheder.',
    'concept.feature1.title': 'Opdagelse af Sårbarheder',
    'concept.feature1.desc': 'De etiske hackere finder og rapporterer sårbarheder i dine systemer, før ondsindede aktører kan udnytte dem.',
    'concept.feature2.title': 'Kontinuerlig Sikkerhed',
    'concept.feature2.desc': 'I stedet for, eller som supplement til årlige pentests, kan det store fællesskab som der er inden for etisk hacking i Danmark udnyttes. Dette skaber mulighed for løbende test af jeres systemer.',
    'concept.feature3.title': 'Samarbejde om Sårbarheder',
    'concept.feature3.desc': 'Defend Denmark og de etiske hackere, hjælper jer med at forstå jeres digitale landskab og dets sikkerhed.',
    'concept.feature4.title': 'Belønningssystem',
    'concept.feature4.desc': 'Fair kompensation ydes til de etiske hackere, der hjælper med at forbedre jeres sikkerhed, jo værre en sårbarhed, jo større en dusør.',
    'concept.why.title': 'Hvorfor Vælge Bug Bounty Programmer?',
    'concept.why.benefit1': 'Ofte mere omkostningseffektiv end traditionelle pentests. Bug Bounty er en betal-per-sårbarhed model',
    'concept.why.benefit2': 'Adgang til divers ekspertise fra de danske etiske hackere',
    'concept.why.benefit3': 'Jeres systemer bliver kontinuerligt testet med nye øjne og nye færdigheder',
    'concept.why.benefit4': 'Et omdømme som en virksomhed der tager cybersikkerhed seriøst',
    'concept.why.tagline': 'En forpligtigelse til at kontinuerligt at blive testet, viser jeres dedikation til at holde jeres systemer sikre.',

    // Bug Bounty Steps
    'steps.badge': 'Sådan Fungerer Det',
    'steps.title': 'Bug Bounty Proces',
    'steps.subtitle': 'Vores 8-trins tilgang sikrer grundig sikkerhedstest og ansvarlig sårbarhedshåndtering for danske organisationer.',
    'steps.1.title': 'Brug Talentet',
    'steps.1.desc': 'Vi engagerer Danmarks dygtigste etiske hackere til at styrke jeres digitale forsvar.',
    'steps.2.title': 'Kom i gang på platformen',
    'steps.2.desc': 'Vores onboarding er simpel, og hackerne begynder deres arbejde med det samme.',
    'steps.3.title': 'Simulér Rigtige Angreb',
    'steps.3.desc': 'Vores hackere simulérer de reelle trusselaktørers metoder mod dine systemer.',
    'steps.4.title': 'Validér Sårbarheder',
    'steps.4.desc': 'Vores team verificerer hver en sårbarhed, vurderer alvorlighed og sørger for at alt er dokumenteret.',
    'steps.5.title': 'Modtag handlingsrettet viden',
    'steps.5.desc': 'Modtag detaljeret teknisk dokumentation og praktisk råd om fix.',
    'steps.6.title': 'Dusører for sårbarheder',
    'steps.6.desc': 'Kompensér de etiske hackere for godkendte og vigtige sårbarheder. Dusøren stiger med sårbarhedens alvorlighed.',
    'steps.7.title': 'Bidrag til Fællesskabet',
    'steps.7.desc': 'En procentdel af hver dusør støtter det digitale Danmark via Fællesskabsfonden.',
    'steps.8.title': 'Ansvarlig Offentliggørelse',
    'steps.8.desc': 'Defend Denmark faciliterer en sikker kanal til offentliggørelse af vigtige sårbarheder, sådan skaber vi et sikrere digitalt Danmark.',
    
    // Community Fund
    'fund.hero.title': 'Fællesskabsfonden',
    'fund.hero.subtitle': 'Styrker Danmarks cybersikkerhed gennem fællesskabsdrevet innovation og støtte',
    'fund.badge': 'Fællesskabseffekt',
    'fund.title': 'Fællesskabsfonden',
    'fund.subtitle': 'Cybersikkerhed for alle',
    'fund.intro.desc1': 'Vores bug bounty platform er unik ved at være drevet af fællesskabet. Med en fælles pulje, der finansieres af virksomheder, der investerer i deres egen sikkerhed, men som ved at forbedre deres egen sikkerhed også ønsker at bidrage til at beskytte Danmark. Samtidig er fonden designet til at gavne f.eks. velgørenhedsorganisationer, start-ups og offentlige institutioner med begrænsede ressourcer.',
    'fund.intro.desc2': 'Fonden er baseret på det sociale ansvar hos de organisationer og virksomheder, der har budgettet til at finansiere deres eget bug bounty program og viser vilje til at hjælpe med at finansiere et system designet til sikring af fællesskabet som helhed.',
    'fund.intro.desc3': 'Fællesskabsfonden er designet til de organisationer, der ikke har  økonomiske midler, og er samtidig en måde at opfordre etiske hackere til at rapportere alle de sårbarheder som de kunne støde på, uanset hvem der er påvirket.',
    'fund.activate.title': 'Lad os udnytte ekspertisen',
    'fund.activate.desc1': 'Med fællesskabsfonden skaber vi et incitamentssystem, hvor   ekspertisen fra etiske hackere bruges til fordel for fællesskabet. Dusører udbetales fra fonden for fund af sårbarheder, som der rapporteres til Defend Denmark, hos virksomheder eller institutioner, der ikke har midlerne til selv at være på platformen.',
    'fund.activate.desc2': 'Defend Denmarks fremtidige vision er, at alle virksomheder og institutioner i Danmark kan bruge bug bounty platformen til at øge deres cybersikkerhed.',
    'fund.structure.title': 'Fondens struktur',
    'fund.structure.desc1': 'Fællesskabsfonden finansieres på den ene side af Defend Denmarks kunder og på den anden side af fællesskabet af etiske hackere.',
    'fund.structure.desc2': 'Kundens bidrag er baseret på de betalte dusører, oven på disse dusører tilføjes et fladt gebyr på 10%, som er kundens bidrag til fonden, hver gang de betaler for en sårbarhed. Fællesskabsfonden vokser derfor med hver sårbarhed som der bliver fundet.',
    'fund.structure.desc3': 'Etiske hackere kan også yde frivillige bidrag til fonden fra deres egne dusører som de får udbetalt.',
    'fund.structure.desc4': 'Dusører udbetalt fra fonden korrelerer med hvad der er indestående i fonden på et givent tidspunkt, samt alvorligheden af den rapporterede sårbarhed.',
    'fund.collab.title': 'Samarbejde om  Sikkerhed',
    'fund.collab.desc': 'Virksomheder og etiske hackere bidrager sammen til at styrke Danmarks samlede cybersikkerhedspostur.',
    'fund.nonprofit.title': 'Non-Profit Support',
    'fund.nonprofit.desc': 'Fonden hjælper med at fremme ansvarlig offentliggørelse af sårbarheder hos organisationer som ikke har midlerne til selv at betale for det.',
    'fund.impact.title': 'Voksende Effekt',
    'fund.impact.desc': 'Efterhånden som flere organisationer deltager, vokser fonden så den kan støtte offentliggøreslse af sårbarheder',
    'fund.fundTitle': 'Fællesskabsfond',
    'fund.fundDesc': 'Sparer midler sammen til at beskytte Danmarks digitale infrastruktur',
    'fund.companyContrib': 'Virksomhedsbidrag',
    'fund.expertContrib': 'Hackerbidrag',
    'fund.prelaunch': 'Aktuel saldo',
    'fund.launchText': 'Fonden vokser med hver fundet sårbarhed. Virksomheder bidrager med 10% oven i hver bounty-betaling.',
    
    // Footer
    'footer.tagline': 'Sikrer det digitale Danmark med etisk hacking',
    'footer.platform': 'Platform',
    'footer.community': 'Fællesskab',
    'footer.communityFund': 'Fællesskabsfonden',
    'footer.company': 'Virksomhed',
    'footer.companyName': 'Defend Denmark ApS',
    'footer.address1': 'Nørrebrogade 45D 4TH',
    'footer.address2': '2200 København N, DK',
    'footer.about': 'Om os',
    'footer.forResearchers': 'For Etiske Hackere',
    'footer.forCompanies': 'For Virksomheder',
    'footer.copyright': '© 2025 Defend Denmark. Alle rettigheder forbeholdes.',
    'footer.prelaunch.title': 'Bliv en del af Defend Denmark',
    'footer.prelaunch.description': 'Uanset om du er etisk hacker eller en virksomhed som ønsker at arbejde med etiske hackere, er vi ivrige efter at byde dig velkommen på platformen. Udfyld venligst formularen, så vender vi tilbage til dig hurtigst muligt.',
    'footer.prelaunch.button': 'Skriv dig op',
    
    // Compliance Hub
    'compliance.hub.title': 'Bug Bounty for Compliance',
    'compliance.hub.subtitle': 'Kontinuerlig, evidensbaseret sikkerhedstest, der mapper direkte til EU\'s cybersikkerhedsregulering — DORA, NIS2 og Cyber Resilience Act.',
    'compliance.hub.intro': 'Moderne EU-regulering på cyberområdet forventer løbende sårbarhedshåndtering, koordineret offentliggørelse og dokumenteret evidens. Defend Denmark leverer crowdsourced sikkerhedstest, der producerer netop dét — kontinuerlig dækning, klassificerede fund og audit-klare rapporter til jeres tilsynsmyndighed.',
    'compliance.hub.frameworks.title': 'Vælg jeres regulering',
    'compliance.hub.frameworks.subtitle': 'Hver regulering har sin egen side med artikel-for-artikel-mapping af, hvordan vores service opfylder kravet, og hvilken dokumentation vi leverer.',

    'compliance.hub.dora.title': 'DORA',
    'compliance.hub.dora.full': 'Digital Operational Resilience Act',
    'compliance.hub.dora.summary': 'EU-forordning i kraft siden januar 2025. Stiller krav om årlig digital operationel modstandsdygtighedstest for finansielle enheder. Vi opfylder Artikel 24-25 gennem kontinuerlig test og forbereder jer til TLPT.',
    'compliance.hub.dora.cta': 'Se DORA-dækning',

    'compliance.hub.nis2.title': 'NIS2',
    'compliance.hub.nis2.full': 'NIS2-direktivet',
    'compliance.hub.nis2.summary': 'Implementeret i dansk ret som NIS2-loven og dækker 18 sektorer af væsentlige og vigtige enheder. Vi leverer Artikel 21-evidens for effektiv sårbarhedshåndtering og Artikel 12-koordineret offentliggørelse.',
    'compliance.hub.nis2.cta': 'Se NIS2-dækning',

    'compliance.hub.cra.title': 'CRA',
    'compliance.hub.cra.full': 'Cyber Resilience Act',
    'compliance.hub.cra.summary': 'EU-forordning for produkter med digitale elementer. Hovedforpligtelser fra december 2027. Vi etablerer Artikel 13-politikken for koordineret offentliggørelse af sårbarheder og leverer dokumentation til konformitetsvurderingen.',
    'compliance.hub.cra.cta': 'Se CRA-dækning',

    'compliance.hub.cta.title': 'I tvivl om hvilken regulering der gælder for jer?',
    'compliance.hub.cta.subtitle': 'Book en 30-minutters konsultation. Vi mapper jeres forpligtelser op imod det, vi leverer.',
    'compliance.hub.cta.button': 'Book en konsultation',

    // Compliance — shared section labels
    'compliance.section.requires': 'Hvad reguleringen kræver',
    'compliance.section.fits': 'Hvordan vores service opfylder hver artikel',
    'compliance.section.evidence': 'Dokumentation og rapporter vi leverer',
    'compliance.section.local': 'Dansk kontekst',
    'compliance.coverage.col.article': 'Artikel-reference',
    'compliance.coverage.col.deliverable': 'Sådan opfylder Defend Denmark det',
    'compliance.cta.download': 'Download eksempel på compliance-rapport',
    'compliance.cta.book': 'Book en konsultation',
    'compliance.cta.note': 'PDFer — eksempler på de artefakter en Defend Denmark-kunde modtager, samt aftalen alle forskere underskriver',
    'compliance.cta.examples': 'Se eksempler på sårbarhedsrapporter',
    'compliance.cta.examples.label': 'Vælg en sårbarhedstype',
    'compliance.cta.examples.idor': 'IDOR — Insecure Direct Object Reference',
    'compliance.cta.examples.bxss': 'Blind XSS',
    'compliance.cta.examples.rce': 'Remote Code Execution',
    'compliance.cta.agreement': 'Se Defenders-aftalen',

    // DORA page
    'compliance.dora.seo.title': 'DORA Compliance med Bug Bounty | Defend Denmark',
    'compliance.dora.seo.description': 'Sådan opfylder Defend Denmark DORA Artikel 24, 25 og 45 gennem kontinuerlig, crowdsourced sikkerhedstest for finansielle enheder. Artikel-for-artikel-mapping af leverancer.',
    'compliance.dora.hero.title': 'DORA',
    'compliance.dora.hero.subtitle': 'Kontinuerlig, evidensbaseret sikkerhedstest der mapper direkte til DORA Artikel 24, 25 og 45 — og forbereder jer til Threat-Led Penetration Testing under Artikel 26.',
    'compliance.dora.what.title': 'Hvad er DORA?',
    'compliance.dora.what.body': 'DORA er EU-forordningen om digital operationel modstandsdygtighed for den finansielle sektor. Den har været i kraft siden 17. januar 2025 og gælder for banker, forsikringsselskaber, investeringsselskaber, betalingsinstitutter, kryptoaktiv-tjenesteudbydere og de kritiske ICT-tredjepartsudbydere, der betjener dem.',

    'compliance.dora.req.intro': 'DORA Kapitel II og IV pålægger finansielle enheder konkrete test- og sårbarhedshåndteringsforpligtelser. De artikler, der er mest relevante for løbende sikkerhedstest, er:',
    'compliance.dora.req.1.article': 'Artikel 6',
    'compliance.dora.req.1.title': 'ICT-risikostyringsramme',
    'compliance.dora.req.1.body': 'Finansielle enheder skal etablere en solid, omfattende og veldokumenteret ICT-risikostyringsramme, der dækker identificering, beskyttelse, detektion, respons og genopretning.',
    'compliance.dora.req.2.article': 'Artikel 24',
    'compliance.dora.req.2.title': 'Generelle krav til digital operationel modstandsdygtighedstest',
    'compliance.dora.req.2.body': 'Etablerer et solidt, omfattende digitalt operationelt modstandsdygtighedstestprogram som integreret del af ICT-risikostyringsrammen, med risikobaserede metoder og fuld dokumentation.',
    'compliance.dora.req.3.article': 'Artikel 25',
    'compliance.dora.req.3.title': 'Test af ICT-værktøjer og -systemer',
    'compliance.dora.req.3.body': 'Test af ICT-værktøjer og -systemer skal omfatte sårbarhedsvurderinger og scanninger, open source-analyser, netværkssikkerhedsvurderinger, gap-analyser, fysiske sikkerhedsreviews, kildekodereviews, scenariebaserede tests, kompatibilitetstest, performancetest, end-to-end-test og penetrationstest — proportional med risikoen.',
    'compliance.dora.req.4.article': 'Artikel 26-27',
    'compliance.dora.req.4.title': 'Avanceret test — Threat-Led Penetration Testing (TLPT)',
    'compliance.dora.req.4.body': 'Udpegede enheder gennemfører TLPT mindst hvert tredje år efter TIBER-EU-rammerne, udført af kvalificerede interne eller eksterne testere, der opfylder Artikel 27.',
    'compliance.dora.req.5.article': 'Artikel 45',
    'compliance.dora.req.5.title': 'Aftaler om informationsdeling om cybertrusler',
    'compliance.dora.req.5.body': 'Finansielle enheder kan udveksle cyberthreat-information og efterretning — herunder kompromisindikatorer og taktikker — inden for betroede fællesskaber for at styrke digital operationel modstandsdygtighed.',
    'compliance.dora.req.6.article': 'Artikel 13',
    'compliance.dora.req.6.title': 'Læring og udvikling',
    'compliance.dora.req.6.body': 'Enheder skal monitorere effektiviteten af deres digitale operationelle modstandsdygtighedsstrategi, samle læring fra tests og hændelser og føre den tilbage i ICT-risikostyringsrammen.',

    'compliance.dora.coverage.intro': 'Hver Defend Denmark-leverance herunder mapper direkte til en DORA-artikel. Vores rapporter er struktureret, så I kan overdrage dem til Finanstilsynet og pege på den specifikke forpligtelse, hver artefakt opfylder.',
    'compliance.dora.coverage.1.article': 'Artikel 6 — ICT-risikostyringsramme',
    'compliance.dora.coverage.1.how': 'Kontinuerlig crowdsourced test producerer løbende identificering, detektion og respons-evidens på tværs af alle ICT-systemer i scope. Fund klassificeres efter alvorlighed, aktiv og CWE, så de passer direkte ind i jeres risikoregister.',
    'compliance.dora.coverage.2.article': 'Artikel 24 — Modstandsdygtighedstestprogram',
    'compliance.dora.coverage.2.how': 'Defend Denmark fungerer som et dokumenteret testprogram: scope, metode, frekvens og risikobaseret dækning er beskrevet skriftligt. Årlige programresuméer produceres til tilsynsmyndighedernes gennemgang.',
    'compliance.dora.coverage.3.article': 'Artikel 25 — Test af ICT-værktøjer og -systemer',
    'compliance.dora.coverage.3.how': 'Vi leverer de testmetoder, Artikel 25 nævner, i en kontinuerlig form: sårbarhedsvurderinger, scanninger, netværkssikkerhedsvurderinger, kildekodereviews (hvor relevant), scenariebaserede tests og penetrationstest — udført af verificerede etiske hackere hen over året, ikke som en engangs-audit.',
    'compliance.dora.coverage.4.article': 'Artikel 26 — Forberedelse til TLPT',
    'compliance.dora.coverage.4.how': 'For udpegede enheder under TLPT hærder vores kontinuerlige dækning aktiverne og afdækker problemer, før den threat-led test går i gang. Vi erstatter ikke TLPT (som kræver Artikel 27-testere); vi reducerer fundene og forbedrer udfaldet.',
    'compliance.dora.coverage.5.article': 'Artikel 45 — Informationsdeling om cybertrusler',
    'compliance.dora.coverage.5.how': 'Vores koordinerede kanal for offentliggørelse af sårbarheder mellem hackere og jeres sikkerhedsteam er i sig selv en Artikel 45-aftale om informationsdeling. Fund, indikatorer og remediation-vejledning flyder ind i jeres betroede fællesskab.',
    'compliance.dora.coverage.6.article': 'Artikel 13 — Læring og udvikling',
    'compliance.dora.coverage.6.how': 'Periodiske ledelsesresuméer — MTTR pr. alvorlighed, fundtæthed, CWE-fordeling, retest-resultater — leverer det lessons-learned-input, Artikel 13 forventer, klar til at føres tilbage i ICT-risikorammen.',

    'compliance.dora.evidence.1': 'Rapport pr. fund med CVSS-baseret alvorlighed, reproduktionstrin, berørte aktiver og remediation-vejledning.',
    'compliance.dora.evidence.2': 'Triage-tidsstempler og SLA-evidens, der dokumenterer kontinuerlig dækning hen over teståret.',
    'compliance.dora.evidence.3': 'Remediation-tracking og retest-validering jf. Artikel 24(5) krav om intern validering.',
    'compliance.dora.evidence.4': 'Årligt resumé af det digitale operationelle modstandsdygtighedstestprogram i tråd med Artikel 24.',
    'compliance.dora.evidence.5': 'Periodiske ledelsesattestationer egnet til bestyrelsesrapportering og tilsynsdialog.',
    'compliance.dora.evidence.6': 'Aggregerede metrikker: dækning, MTTR, fordeling af fund efter alvorlighed, aktivklasse og sårbarhedstype (CWE).',

    'compliance.dora.local.title': 'Danmark',
    'compliance.dora.local.body': 'I Danmark fører Finanstilsynet tilsyn med DORA og er den kompetente myndighed, der sikrer, at danske finansielle enheder efterlever forordningen. Vores rapportering er struktureret til at kunne anvendes direkte i tilsynsdialog med Finanstilsynet.',

    // NIS2 page
    'compliance.nis2.seo.title': 'NIS2 Compliance med Vulnerability Disclosure | Defend Denmark',
    'compliance.nis2.seo.description': 'Defend Denmark leverer Artikel 21(2)(e) sårbarhedshåndtering, Artikel 21(2)(f) effektivitetsvurdering og Artikel 12 koordineret offentliggørelse for væsentlige og vigtige enheder under NIS2 / NIS2-loven.',
    'compliance.nis2.hero.title': 'NIS2',
    'compliance.nis2.hero.subtitle': 'Artikel-for-artikel-dækning af sårbarhedshåndtering, koordineret offentliggørelse og effektivitetsvurdering for væsentlige og vigtige enheder på tværs af alle 18 sektorer.',
    'compliance.nis2.what.title': 'Hvad er NIS2?',
    'compliance.nis2.what.body': 'NIS2 er EU-direktivet, der markant udvider cybersikkerhedsforpligtelserne på tværs af unionen. Det er implementeret i dansk ret som NIS2-loven og rammer "væsentlige" og "vigtige" enheder i 18 sektorer — herunder energi, transport, sundhed, digital infrastruktur, offentlig forvaltning, fremstilling og fødevarer.',

    'compliance.nis2.req.intro': 'NIS2 pålægger væsentlige og vigtige enheder konkrete pligter omkring cybersikkerhed, sårbarhedshåndtering og offentliggørelse. De artikler, der er mest relevante for løbende sikkerhedstest, er:',
    'compliance.nis2.req.1.article': 'Artikel 12',
    'compliance.nis2.req.1.title': 'Koordineret offentliggørelse af sårbarheder og en europæisk sårbarhedsdatabase',
    'compliance.nis2.req.1.body': 'Medlemsstaterne udpeger et CSIRT som koordinator for koordineret offentliggørelse af sårbarheder. ENISA driver en europæisk sårbarhedsdatabase, der gør det muligt at dele sårbarhedsoplysninger på unionsniveau.',
    'compliance.nis2.req.2.article': 'Artikel 21(1)',
    'compliance.nis2.req.2.title': 'Cybersikkerhedsforanstaltninger til risikostyring',
    'compliance.nis2.req.2.body': 'Væsentlige og vigtige enheder skal træffe passende og forholdsmæssige tekniske, operationelle og organisatoriske foranstaltninger for at håndtere risici for sikkerheden af net- og informationssystemer.',
    'compliance.nis2.req.3.article': 'Artikel 21(2)(b)',
    'compliance.nis2.req.3.title': 'Hændelseshåndtering',
    'compliance.nis2.req.3.body': 'Enheder skal etablere dokumenterede processer for hændelseshåndtering, herunder detektion, analyse, inddæmning og respons.',
    'compliance.nis2.req.4.article': 'Artikel 21(2)(e)',
    'compliance.nis2.req.4.title': 'Sikkerhed i indkøb, udvikling og vedligeholdelse — herunder sårbarhedshåndtering og offentliggørelse',
    'compliance.nis2.req.4.body': 'Enheder skal drive processer for sårbarhedshåndtering og offentliggørelse som del af sikringen af de systemer, de indkøber, udvikler og vedligeholder.',
    'compliance.nis2.req.5.article': 'Artikel 21(2)(f)',
    'compliance.nis2.req.5.title': 'Politikker og procedurer til at vurdere effektivitet af cybersikkerhedsforanstaltninger',
    'compliance.nis2.req.5.body': 'Enheder skal vedtage politikker og procedurer — for eksempel regelmæssig test — til at vurdere effektiviteten af deres cybersikkerhedsforanstaltninger til risikostyring.',
    'compliance.nis2.req.6.article': 'Artikel 23',
    'compliance.nis2.req.6.title': 'Indberetningsforpligtelser',
    'compliance.nis2.req.6.body': 'Væsentlige hændelser skal meddeles CSIRT eller den kompetente myndighed — tidlig advarsel inden for 24 timer, hændelsesnotifikation inden for 72 timer og endelig rapport inden for én måned.',

    'compliance.nis2.coverage.intro': 'Hver Defend Denmark-leverance herunder mapper direkte til en NIS2-artikel. Vores rapporter er designet til at kunne fremlægges som evidens for en dansk tilsynsmyndighed — peg på den relevante artikel, overdrag artefakten.',
    'compliance.nis2.coverage.1.article': 'Artikel 12 — Koordineret offentliggørelse af sårbarheder',
    'compliance.nis2.coverage.1.how': 'Defend Denmark fungerer som jeres CVD-indgang — verificerede etiske hackere indrapporterer, vi triager, I modtager strukturerede rapporter. Programmet er i tråd med medlemsstatens CVD-politik og fødes ind i ENISA\'s europæiske sårbarhedsdatabase, hvor relevant.',
    'compliance.nis2.coverage.2.article': 'Artikel 21(2)(e) — Sårbarhedshåndtering og offentliggørelse',
    'compliance.nis2.coverage.2.how': 'Et dokumenteret, audit-klart sårbarhedshåndteringsprogram: indrapportering, klassificering, alvorlighedsscoring, remediation-tracking og retest-validering. Programmet er i sig selv den evidens, Artikel 21(2)(e) efterspørger.',
    'compliance.nis2.coverage.3.article': 'Artikel 21(2)(f) — Effektivitetsvurdering',
    'compliance.nis2.coverage.3.how': 'Kontinuerlig test producerer effektivitetsmetrikker — MTTR pr. alvorlighed, fundtæthed over tid, retest-bestået-rate, dækningsbredde. Det er præcis de "politikker og procedurer til at vurdere effektivitet", artiklen kræver.',
    'compliance.nis2.coverage.4.article': 'Artikel 21(2)(b) — Input til hændelseshåndtering',
    'compliance.nis2.coverage.4.how': 'Rapporter pr. fund indeholder reproduktionstrin, alvorlighed og opdagelsestidspunkt — direkte anvendelige som input til jeres hændelseshåndtering, når et fund krydser væsentlighedstærsklen.',
    'compliance.nis2.coverage.5.article': 'Artikel 23 — Understøttelse af notifikations-tidslinje',
    'compliance.nis2.coverage.5.how': 'Fund når jer med tidsstempler, der understøtter 24-timers tidlig advarsel og 72-timers hændelsesnotifikation. Selve notifikationen til CSIRT forbliver jeres ansvar; tidsevidensen ligger i vores rapporter.',
    'compliance.nis2.coverage.6.article': 'Artikel 21(1) — Risikostyringsforanstaltninger',
    'compliance.nis2.coverage.6.how': 'Dækningsrapporter dokumenterer, at den tekniske foranstaltning kontinuerlig tredjepartstest er taget i brug i forhold til risikoprofilen for jeres net- og informationssystemer.',

    'compliance.nis2.evidence.1': 'Dokumenteret CVD-politik (koordineret offentliggørelse af sårbarheder) i tråd med Artikel 12.',
    'compliance.nis2.evidence.2': 'Rapport pr. fund med klassificering af alvorlighed, reproduktionstrin og remediation-tracking.',
    'compliance.nis2.evidence.3': 'Effektivitetsmetrikker — MTTR pr. alvorlighed, retest-bestået-rate, fundtæthed — til Artikel 21(2)(f)-rapportering.',
    'compliance.nis2.evidence.4': 'Årligt programresumé egnet til overdragelse til kompetent myndighed eller sektortilsynsmyndighed.',
    'compliance.nis2.evidence.5': 'Opdagelsestidsstempler og evidensspor til understøttelse af Artikel 23 notifikations-tidslinjer.',

    'compliance.nis2.local.title': 'Danmark',
    'compliance.nis2.local.body': 'I Danmark føres tilsyn med NIS2-loven af Digitaliseringsstyrelsen inden for den digitale sektor i Danmark. Vores offentliggørelsesprogram og audit-klare rapporter er designet til at falde direkte ind i den dokumentation, en dansk tilsynsmyndighed forventer at se.',

    // CRA page
    'compliance.cra.seo.title': 'Cyber Resilience Act Compliance | Defend Denmark',
    'compliance.cra.seo.description': 'Defend Denmark opfylder CRA Artikel 13 fabrikantforpligtelser og Bilag I Del II sårbarhedshåndteringskrav gennem kontinuerlig opdagelse, drift af CVD-politik og dokumentation klar til konformitetsvurdering.',
    'compliance.cra.hero.title': 'CRA',
    'compliance.cra.hero.subtitle': 'Artikel-for-artikel-dækning af fabrikantforpligtelser og Bilag I sårbarhedshåndtering for ethvert produkt med digitale elementer, der sælges i EU.',
    'compliance.cra.what.title': 'Hvad er Cyber Resilience Act?',
    'compliance.cra.what.body': 'CRA er EU-forordningen, der trådte i kraft i december 2024, med hovedforpligtelser, der gælder fra december 2027. Den dækker ethvert produkt med digitale elementer, der sælges i EU — IoT-enheder, software, hardware med konnektivitet — og gælder for fabrikanter, importører og distributører.',

    'compliance.cra.req.intro': 'CRA kombinerer essentielle cybersikkerhedskrav (Bilag I), fabrikantpligter (Artikel 13), indberetningsforpligtelser (Artikel 14) og en dokumentationsregime (Artikel 31), der fører til konformitetsvurdering og CE-mærkning. De artikler, der er mest relevante for løbende sikkerhedstest, er:',
    'compliance.cra.req.1.article': 'Artikel 6 + Bilag I Del I',
    'compliance.cra.req.1.title': 'Essentielle cybersikkerhedskrav til produkter med digitale elementer',
    'compliance.cra.req.1.body': 'Produkter skal designes, udvikles og produceres, så de sikrer et passende cybersikkerhedsniveau baseret på risiko — herunder leveres uden kendte udnyttelige sårbarheder og være beskyttet mod uautoriseret adgang.',
    'compliance.cra.req.2.article': 'Artikel 13',
    'compliance.cra.req.2.title': 'Fabrikanters forpligtelser',
    'compliance.cra.req.2.body': 'Fabrikanter skal drive sårbarhedshåndteringsprocesser i hele supportperioden, herunder en politik for koordineret offentliggørelse af sårbarheder og et fælles kontaktpunkt for indrapportering af sårbarheder.',
    'compliance.cra.req.3.article': 'Bilag I Del II',
    'compliance.cra.req.3.title': 'Krav til sårbarhedshåndtering',
    'compliance.cra.req.3.body': 'Identificér og dokumentér sårbarheder; afhjælp dem uden forsinkelse via sikkerhedsopdateringer; udfør regelmæssige test og reviews; del information om afhjulpne sårbarheder; drif en politik for koordineret offentliggørelse.',
    'compliance.cra.req.4.article': 'Artikel 14',
    'compliance.cra.req.4.title': 'Fabrikanters indberetningsforpligtelser',
    'compliance.cra.req.4.body': 'Aktivt udnyttede sårbarheder og alvorlige hændelser skal indberettes til ENISA — tidlig advarsel inden for 24 timer, fuld notifikation inden for 72 timer og endelig rapport inden for 14 dage.',
    'compliance.cra.req.5.article': 'Artikel 31',
    'compliance.cra.req.5.title': 'Teknisk dokumentation',
    'compliance.cra.req.5.body': 'Fabrikanter skal udarbejde og opbevare teknisk dokumentation, der dokumenterer overensstemmelse med de essentielle krav — herunder cybersikkerhedsrisikovurderingen og sårbarhedshåndteringsprocesserne.',
    'compliance.cra.req.6.article': 'Artikel 32',
    'compliance.cra.req.6.title': 'Procedurer for konformitetsvurdering',
    'compliance.cra.req.6.body': 'Inden et produkt bringes i omsætning, gennemfører fabrikanten en konformitetsvurdering, der dokumenterer opfyldelse af de essentielle krav — vejen afhænger af, om produktet er standard, vigtigt eller kritisk.',

    'compliance.cra.coverage.intro': 'Hver Defend Denmark-leverance herunder mapper direkte til en CRA-artikel eller et Bilag I-krav. Vores output produceres i en form, der går direkte ind i jeres tekniske dokumentationsfil og konformitetsvurdering.',
    'compliance.cra.coverage.1.article': 'Artikel 13 + Bilag I Del II.5 — CVD-politik',
    'compliance.cra.coverage.1.how': 'Defend Denmark leverer den dokumenterede CVD-politik og driver det fælles kontaktpunkt for indrapportering af sårbarheder. Indrapporteringer modtages, triages og spores under jeres navn — direkte opfyldelse af fabrikantforpligtelsen.',
    'compliance.cra.coverage.2.article': 'Bilag I Del II.1 — Identificér og dokumentér sårbarheder',
    'compliance.cra.coverage.2.how': 'Kontinuerlig ekstern sårbarhedsopdagelse af verificerede etiske hackere gennem hele produktets supportperiode. Hvert fund dokumenteres med berørt komponent, version, alvorlighed og reproduktionstrin.',
    'compliance.cra.coverage.3.article': 'Bilag I Del II.2 — Afhjælp uden forsinkelse',
    'compliance.cra.coverage.3.how': 'Rapporter pr. fund indeholder vurdering af udnyttelighed og konkret remediation-vejledning, så jeres engineering-team kan udsende rettidige sikkerhedsopdateringer inden for supportperioden.',
    'compliance.cra.coverage.4.article': 'Bilag I Del II.3 — Regelmæssige test og reviews',
    'compliance.cra.coverage.4.how': 'Defend Denmark-programmet er i sig selv et løbende test- og review-regime — bredere end periodiske pentests og proportionalt med produktets risikoprofil. Dækningsrapporter dokumenterer regelmæssigheden.',
    'compliance.cra.coverage.5.article': 'Bilag I Del II.6 — Informationsdeling om sårbarheder',
    'compliance.cra.coverage.5.how': 'Aggregeret og fundbaseret rapportering fødes ind i jeres informationsdelingsforpligtelser og understøtter kommunikation til kunder om afhjulpne sårbarheder.',
    'compliance.cra.coverage.6.article': 'Artikel 14 — 24-timers ENISA-tidslinje',
    'compliance.cra.coverage.6.how': 'Alvorlighedsklassificerede, tidsstemplede fund giver jer det tidlige varslingssignal, der skal bruges til at overholde 24-timers vinduet for ENISA-notifikation om aktivt udnyttede sårbarheder. Selve notifikationen forbliver fabrikantens handling; vi leverer opdagelsesevidens og tidslinje.',
    'compliance.cra.coverage.7.article': 'Artikel 31 — Teknisk dokumentation',
    'compliance.cra.coverage.7.how': 'Rapporter pr. fund, remediation-evidens, retest-validering og CVD-politikkens dokumentation produceres i en form, der går direkte ind i den tekniske dokumentationsfil.',
    'compliance.cra.coverage.8.article': 'Artikel 32 — Konformitetsvurdering',
    'compliance.cra.coverage.8.how': 'Programresuméer og dækningsrapporter kan bruges som evidens for effektiv sårbarhedshåndtering inden for konformitetsvurderingen — uanset om vejen er intern kontrol (standard) eller tredjepartsvurdering (vigtig / kritisk).',

    'compliance.cra.evidence.1': 'Dokumenteret CVD-politik (koordineret offentliggørelse af sårbarheder), der opfylder Artikel 13 og Bilag I Del II.5.',
    'compliance.cra.evidence.2': 'Fælles kontaktpunkt for indrapportering af sårbarheder, drevet af Defend Denmark på fabrikantens vegne.',
    'compliance.cra.evidence.3': 'Rapport pr. fund — berørt komponent, alvorlighed, reproduktionstrin, remediation-vejledning, retest-evidens.',
    'compliance.cra.evidence.4': 'Kontinuerlig dækningsrapportering egnet som input til Artikel 31 teknisk dokumentationsfil.',
    'compliance.cra.evidence.5': 'Tidsstemplet opdagelsesevidens til understøttelse af Artikel 14 24t / 72t / 14-dages ENISA-tidslinje.',
    'compliance.cra.evidence.6': 'Programresuméer anvendelige i Artikel 32 konformitetsvurdering.',

    'compliance.cra.local.title': 'Danmark',
    'compliance.cra.local.body': 'I Danmark varetages tilsyn og markedsovervågning under Cyber Resilience Act af Styrelsen for Samfundssikkerhed (Samsik), som er ansvarlig for at føre revision med fabrikanters efterlevelse af forordningen. Vores offentliggørelsesprogram er bygget til at gå direkte ind i en dansk fabrikants tekniske dokumentation og eftermarkedshåndtering af sårbarheder, klar til Samsiks gennemgang.',

    // Companies Page
    'companies.title': 'For Virksomheder',
    'companies.subtitle': 'Styrk jeres IT-sikkerhed med danske etiske hackere',
    'companies.howItWorks': 'Sådan fungerer det for jer',
    'companies.step1.title': 'Opsæt et program',
    'companies.step1.desc': 'Definér hvad I gerne vil have testet, jeres regler og rammen for dusører for jeres bug bounty program',
    'companies.step2.title': 'Danske hackere tester',
    'companies.step2.desc': 'Verificerede danske etiske hackere begynder at teste jeres systemer for sårbarheder',
    'companies.step3.title': 'Modtag rapporter',
    'companies.step3.desc': 'Vi verificerer og godkender alle rapporter om sårbarheder fra hackerne',
    'companies.step4.title': 'Godkend & betal',
    'companies.step4.desc': 'I betaler kun for reelle og vigtige sårbarheder som bliver fundet',
    'companies.benefit1.title': 'Kontinuerlig sikkerhedstest',
    'companies.benefit1.desc': 'Få jeres systemer testet løbende af etiske hackere med forskellige specialer',
    'companies.benefit2.title': 'Omkostningseffektiv',
    'companies.benefit2.desc': 'Betal kun for reelle sårbarheder der bliver fundet og ikke for den tid der er brugt',
    'companies.benefit3.title': 'Verificerede etiske hackere',
    'companies.benefit3.desc': 'Alle etiske hackere bliver MitID verificerede og godkender reglerne for etisk hacking',
    'companies.benefit4.title': 'Professionel verificering',
    'companies.benefit4.desc': 'Vores egne sikkerhedseksperter verificerer, triagerer og prioriterer alle rapporterede sårbarheder',
    'companies.benefit5.title': 'Hurtig respons',
    'companies.benefit5.desc': 'Kritiske sårbarheder rapporteres inden for 24 timer',
    'companies.benefit6.title': 'Dedikeret support',
    'companies.benefit6.desc': 'Dansk kundeservice, vejledning og teknisk support gennem hele processen',
    
    // About Page
    'about.hero.title': 'Om Defend Denmark',
    'about.hero.subtitle': 'En sikker digital fremtid for Danmark gennem etisk hacking',
    'about.prelaunch.title': 'Nu Live',
    'about.prelaunch.description': 'Defend Denmark er officielt lanceret og operationelt. Vi onboarder aktivt etiske hackere og virksomheder — tag kontakt, hvis I ønsker at komme i gang med et bug bounty program eller vil tilmelde jer som etisk hacker.',
    'about.hackers.title': 'Etiske hackere står klar',
    'about.hackers.description': 'Vi har samlet et talentfuldt fællesskab af etiske hackere, der brænder for cybersikkerhed og er klar til at hjælpe danske virksomheder med at identificere og rette sårbarheder. Vores etiske hackere gennemgår grundig kontrol for at sikre de højeste standarder for professionalisme og integritet.',
    'about.vision.title': 'Vores Vision',
    'about.vision.description': 'At blive Danmarks førende cybersikkerhedsplatform, der fremmer en kultur med proaktiv sikkerhedstest og hjælper virksomheder med at være foran cybertrusler gennem ansvarlig offentliggørelse og samarbejde omkring etisk hacking.',
    'about.researcher.experience': 'Års Erfaring',
    'about.founder.quote': 'Efter selv at have identificeret hundredevis af sårbarheder og arbejdet med de dygtigste danske etiske hackere, gik det op for mig at der ikke var særligt mange danske virksomheder på bug bounty platforme. Dette fik mig til at sætte Defend Denmark i verden, for at hjælpe danske virksomheder med at arbejde med det danske sikkerheds-community om at finde reelle og vigtige sårbarheder i danske virksomheder.',
    'about.discord.title': 'Bliv en del af fællesskabet',
    'about.discord.description': 'Kom i kontakt med andre etiske hackere, bliv opdateret om de nyeste programmer og deltag i bug bounty fællesskabet.',
    'about.discord.button': 'Join os på Discord',
    
    // Researchers Page
    'nav.researchers': 'For Etiske Hackere',
    'researchers.title': 'For Etiske Hackere',
    'researchers.subtitle': 'Tjen penge på dine hacking skills',
    'researchers.howToEarn': 'Sådan bliver du belønnet',
    'researchers.step1.title': 'Tilmeld dig',
    'researchers.step1.desc': 'Opret profil og bliv verificeret som etisk hacker',
    'researchers.step2.title': 'Find sårbarheder',
    'researchers.step2.desc': 'Test de udvalgte danske virksomheders systemer og find sårbarheder',
    'researchers.step3.title': 'Rapportér',
    'researchers.step3.desc': 'Skriv en detaljeret rapport om sårbarheden',
    'researchers.step4.title': 'Verificering',
    'researchers.step4.desc': 'Vi bekræfter sårbarheden og vurderer alvoren',
    'researchers.step5.title': 'Bliv betalt',
    'researchers.step5.desc': 'Modtag en dusør baseret på sårbarhedens kritikalitet',
    'researchers.benefit1.title': 'Høje dusører',
    'researchers.benefit1.desc': 'Konkurrencedygtige dusører baseret på hvor slem sårbarheden er',
    'researchers.benefit2.title': 'Danske virksomheder',
    'researchers.benefit2.desc': 'Arbejd med kendte danske brands og virksomheder',
    'researchers.benefit3.title': 'Hurtig verificering',
    'researchers.benefit3.desc': 'Modtag feedback på den fundne sårbarhed inden for 5 hverdage',
    'researchers.benefit4.title': 'Professionel support',
    'researchers.benefit4.desc': 'Få hjælp til professionel kommunikation med virksomheder',
    'researchers.benefit5.title': 'Gamification',
    'researchers.benefit5.desc': 'Modtag point for alle sårbarheder, også selvom de ikke giver udbetaling',
    'researchers.benefit6.title': 'Juridisk Beskyttelse',
    'researchers.benefit6.desc': 'Sikre rammer for etisk hacking under danske love',
    'researchers.requirements.title': 'Krav',
    'researchers.requirements.citizen': 'Dansk statsborger eller beboer. Adgang til MitID verificering er et krav',
    'researchers.requirements.agreement': 'Indforstået med at skulle acceptere defenders-aftalen —',
    'researchers.requirements.agreement.link': 'se aftalen',
    'researchers.requirements.record': 'Ren straffeattest',
    'researchers.requirements.disclosure': 'Forpligtet til ansvarlig offentliggørelse af sårbarheder',
    
    // Spotlight / Security Researchers Carousel
    'spotlight.title': 'Mød Vores Etisk Hackere',
    'spotlight.subtitle': 'Dygtige etiske hackere som er klar til at finde sårbarheder i danske virksomheder',
    'spotlight.disclaimer': 'Bemærk: Sårbarhederne beskrevet nedenfor er ikke nødvendigvis fund i Defend Denmarks kunder, men også, uafhængig research eller kontraktarbejde, og præsenteres her for at demonstrere de etiske hackeres færdigheder og ekspertise.',
    'spotlight.mitidVerified': 'MitID Verificeret',
    'spotlight.agreementSigned': 'Aftale Underskrevet',
    'spotlight.viewAgreement': 'Se Defenders-aftalen',
    'spotlight.ndaSigned': 'NDA Underskrevet',
    'spotlight.profession': 'Profession',
    'spotlight.specialization': 'Specialisering',
    'spotlight.experience': 'år',
    'spotlight.discoveries': 'Seneste Opdagelser',
    'spotlight.reward': 'Belønning:',
    'spotlight.industry': 'Branche:',
    'spotlight.cvss': 'CVSS:',
    'spotlight.acceptedAs': 'Accepteret som:',
    
    // Fund additional keys
    'fund.howItWorks': 'Sådan Fungerer Fællesskabsfonden',
    'fund.flowchartDesc': 'Fællesskabsfonden skaber et økosystem, hvor virksomheder bidrager til at organisationer som der ikke selv har råd til det, kan blive støttet af etiske hackere. Dette hjælper med at sikre Danmarks digitale infrastruktur.',
    
    // Not Found Page
    'notFound.message': 'Hallo hacker, hvad laver du her ;-) Siden blev ikke fundet',
    'notFound.returnHome': 'Tilbage til Forsiden',
    
    // Common
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('da');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};