import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'da';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.companies': 'For Companies',
    'nav.bugBounty': 'Bug Bounty Platform',
    'nav.communityFund': 'Community Fund',
    'nav.about': 'About',
    
    // Hero Section
    'hero.title': 'A safer digital',
    'hero.titleAccent': 'Denmark',
    'hero.subtitle': 'Defend Denmark is a progressive cyber security company specialising in proactive security measures. We have the country\'s leading ethical hackers which simulate the methods of hackers and thus find security vulnerabilities in software systems of companies and organisations.',
    'hero.bookDemo': 'Book a Demo',
    'hero.learnMore': 'Learn More',
    'hero.earlyAccess': 'Get Early Access',
    'hero.emailPlaceholder': 'Enter your email',
    'hero.joinWaitlist': 'Join Waitlist',
    'hero.waitlistText': 'Be the first to know when we launch in Denmark',
    
    // Preventive Measures
    'preventive.title': 'Preventive measures',
    'preventive.description': 'Our ethical hackers simulate real attacks and find new vulnerabilities in the custom-built software infrastructures that our customers use. By proactively identifying and addressing these issues, we help our customers strengthen their overall security posture and reduce the risk of cyber threats.',
    
    // Bug Bounty Page
    'bugBounty.hero.title': 'Proactive cybersecurity',
    'bugBounty.hero.subtitle': 'Strengthen your digital posture with the best Danish ethical hackers',
    'bugBounty.hero.bookDemo': 'Book a Demo',
    'bugBounty.what.title': 'What is a bug bounty platform?',
    'bugBounty.what.desc1': 'A bug bounty platform is a service that connects organizations with ethical hackers to identify and fix security vulnerabilities in their systems. Organizations create programs offering rewards for discovering and reporting specific types of bugs, such as vulnerabilities in software, websites, or applications. Ethical hackers participate by testing the systems within the agreed-upon scope, providing detailed reports of their findings. The platform facilitates secure communication, manages submissions, and ensures payments are made to defenders who contribute valuable discoveries. This model helps organizations enhance their cyber security posture cost-effectively by leveraging a network of experts.',
    'bugBounty.what.desc2': 'Defend Denmark is a unique, nationwide bug bounty platform that aims to accelerate bug bounty uptake for SMEs and governmental institutions in Denmark by providing an innovative bug bounty platform that eliminates common barriers that have so far prevented rapid uptake of such solutions.',
    'bugBounty.what.desc3': 'Denmark has a large force of skilled ethical hackers, we find them, verify them and make them available to Danish companies. All our defenders are MitID verified and have a clean criminal record, they all agree to testing ethically and within the scope defined by the company.',
    'bugBounty.what.desc4': 'Defend Denmark\'s bug bounty platform is a proactive cyber security initiative that leverages the expertise and skills of ethical hackers for the benefit of our society. This crowdsourced approach harnesses collective efforts to identify and address security vulnerabilities in companies\' systems before they lead to serious breaches, ransomware incidents, or data leaks.',
    'bugBounty.what.desc5': 'Defend Denmark\'s vision is for all companies and organizations in Denmark to have access to the bug bounty platform. This way, we strengthen the security of Denmark\'s digital infrastructure and enhance the resilience of society.',

    // Bug Bounty Concept
    'concept.badge': 'Bug Bounty Programs',
    'concept.title': 'What is a Bug Bounty?',
    'concept.subtitle': 'Bug bounty programs are crowdsourced cybersecurity initiatives where organizations invite ethical hackers to find and report security vulnerabilities in exchange for rewards. This collaborative approach helps identify weaknesses before they can be exploited by malicious actors.',
    'concept.feature1.title': 'Vulnerability Discovery',
    'concept.feature1.desc': 'Security researchers find and report vulnerabilities in your systems before malicious actors can exploit them.',
    'concept.feature2.title': 'Continuous Security',
    'concept.feature2.desc': 'Instead of yearly audits, utilize the power of a large Danish community of ethical hackers to continuously address your systems.',
    'concept.feature3.title': 'Collaborative Defense',
    'concept.feature3.desc': 'Defend Denmark together with the ethical hackers and yourself, helps pinpoint the details about your security posture.',
    'concept.feature4.title': 'Reward System',
    'concept.feature4.desc': 'Fair compensation for researchers who help improve your security posture through responsible disclosure.',
    'concept.why.title': 'Why Choose Bug Bounty Programs?',
    'concept.why.benefit1': 'Cost-effective security testing with pay-per-vulnerability model',
    'concept.why.benefit2': 'Access to diverse expertise from the Danish security community',
    'concept.why.benefit3': 'Continuous security monitoring beyond traditional penetration testing',
    'concept.why.benefit4': 'Enhanced reputation through transparent security practices',
    'concept.why.tagline': 'Strengthen your security posture with the power of the crowd',

    // Bug Bounty Steps
    'steps.badge': 'How It Works',
    'steps.title': 'Bug Bounty Process',
    'steps.subtitle': 'Our comprehensive 8-step approach ensures thorough security testing and responsible vulnerability management for Danish organizations.',
    'steps.1.title': 'Activate Elite Talent',
    'steps.1.desc': 'We engage Denmark\'s most skilled cybersecurity professionals to strengthen your digital defenses.',
    'steps.2.title': 'Launch Security Testing',
    'steps.2.desc': 'Our platform deployment is seamless, and vulnerability discovery begins immediately.',
    'steps.3.title': 'Simulate Real Attacks',
    'steps.3.desc': 'Security experts replicate actual threat actor methodologies against your systems.',
    'steps.4.title': 'Validate Vulnerabilities',
    'steps.4.desc': 'Our team verifies each finding, assesses severity, and prioritizes remediation efforts.',
    'steps.5.title': 'Deliver Actionable Intelligence',
    'steps.5.desc': 'Receive detailed technical documentation and practical remediation guidance.',
    'steps.6.title': 'Reward Discoveries',
    'steps.6.desc': 'Compensate security researchers for validated vulnerabilities through our transparent bounty system.',
    'steps.7.title': 'Contribute to Community',
    'steps.7.desc': 'A percentage of each bounty payment supports Denmark\'s broader cybersecurity ecosystem - The community fund.',
    'steps.8.title': 'Responsible Disclosure',
    'steps.8.desc': 'Defend Denmark provides a secure channel for reporting vulnerabilities, creating a safer digital environment.',
    
    // Community Fund
    'fund.hero.title': 'Community Fund',
    'fund.hero.subtitle': 'Strengthening Denmark\'s cybersecurity through community-driven innovation and support',
    'fund.badge': 'Community Impact',
    'fund.title': 'Denmark Community Fund',
    'fund.subtitle': 'Cyber security for everyone',
    'fund.intro.desc1': 'Our bug bounty platform is unique in that it is community driven. With a fund that is financed by companies that invest in their own security, but who, by increasing their own security, also want to contribute to protecting Denmark. At the same time, the fund is designed to benefit, for example, charities, start-ups and public institutions with limited resources.',
    'fund.intro.desc2': 'The fund is based on the social responsibility of those organizations and companies that have the budget to finance their own bug bounty platform and show a willingness to help finance a system designed for the community as a whole.',
    'fund.intro.desc3': 'The community fund is designed for those who don\'t have the financial means, and at the same time is a way to encourage the defenders to report all incidents of security vulnerabilities in our community, no matter who is affected.',
    'fund.activate.title': 'Let\'s activate expertise',
    'fund.activate.desc1': 'With the community fund, we create an incentive system where the expertise and skills of ethical hackers are activated to benefit the community. Rewards are paid from the fund for security vulnerabilities that are reported to Defend Denmark, at companies or institutions that do not have the funds to pay rewards.',
    'fund.activate.desc2': 'With this, we approach Denmark\'s cyber security in a holistic way, but Defend Denmark\'s future vision is that all companies and institutions in Denmark can use the bug bounty platform to increase their cyber security.',
    'fund.disclosure.title': 'Responsible vulnerability disclosure',
    'fund.disclosure.desc': 'Responsible vulnerability disclosure is integrated with Defend Denmark\'s bug bounty platform and differentiates it from other cyber security solutions. We focus on the digital security of the community as a whole, not just our customers.',
    'fund.structure.title': 'Structure of the fund',
    'fund.structure.desc1': 'The community fund is financed on the one hand by Defend Denmark\'s customers and on the other hand by the community of ethical hackers.',
    'fund.structure.desc2': 'The customer\'s contribution is based on the paid reward money for security vulnerabilities, but on top of those payments a 10% flat fee is added, which is the customer\'s contribution to the fund every time they pay for a vulnerability. The community fund therefore grows with each security vulnerability found.',
    'fund.structure.desc3': 'Ethical hackers can also make voluntary contributions to the fund from their own reward money.',
    'fund.structure.desc4': 'The reward money paid out of the fund takes into account its status at any given time and the potential impact of the vulnerabilities on Denmark\'s digital community.',
    'fund.collab.title': 'Collaborative Security',
    'fund.collab.desc': 'Companies and security experts contribute together to strengthen Denmark\'s overall cybersecurity posture.',
    'fund.nonprofit.title': 'Non-Profit Support',
    'fund.nonprofit.desc': 'Fund security assessments for organizations protecting sensitive citizen data and critical services.',
    'fund.impact.title': 'Growing Impact',
    'fund.impact.desc': 'As more organizations join, the fund grows to support an expanding network of digital security initiatives.',
    'fund.stayInformed': 'Stay Informed',
    'fund.updatesText': 'Get updates on community fund milestones and impact stories.',
    'fund.emailPlaceholder': 'Your email',
    'fund.subscribe': 'Subscribe',
    'fund.fundTitle': 'Community Fund',
    'fund.fundDesc': 'Building resources to protect Denmark\'s digital infrastructure',
    'fund.companyContrib': 'Company Contributions',
    'fund.expertContrib': 'Expert Contributions',
    'fund.prelaunch': 'Pre-launch phase',
    'fund.launchText': 'Fund values will be displayed once Defend Denmark officially launches and begins operations.',
    
    // Footer
    'footer.stayConnected': 'Stay Connected',
    'footer.newsletterText': 'Get updates on Defend Denmark\'s launch, cybersecurity insights, and community initiatives delivered to your inbox.',
    'footer.emailPlaceholder': 'Enter your email',
    'footer.subscribe': 'Subscribe',
    'footer.tagline': 'Securing Denmark\'s digital future through collaborative cybersecurity excellence.',
    'footer.platform': 'Platform',
    'footer.bugBounty': 'Bug Bounty',
    'footer.securityTesting': 'Security Testing',
    'footer.vulnManagement': 'Vulnerability Management',
    'footer.responsibleDisclosure': 'Responsible Disclosure',
    'footer.community': 'Community',
    'footer.communityFund': 'Community Fund',
    'footer.securityExperts': 'Security Experts',
    'footer.events': 'Events',
    'footer.resources': 'Resources',
    'footer.company': 'Company',
    'footer.companyName': 'Defend Denmark ApS',
    'footer.address1': 'Reventlowsgade 18, 3. th',
    'footer.address2': '1651 København V, DK',
    'footer.email': 'info@defenddenmark.dk',
    'footer.about': 'About',
    'footer.forResearchers': 'For Security Researchers',
    'footer.forCompanies': 'For Companies',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2025 Defend Denmark. All rights reserved.',
    'footer.sisterCompany': 'Sister company to Defend Iceland',
    'footer.prelaunch.title': 'Sign up for Defend Denmark',
    'footer.prelaunch.description': 'Whether you are a security researcher or a company who wishes to work with ethical hackers, we are eager to welcome you on the platform. Please fill out the form and we will get back to you as soon as possible.',
    'footer.prelaunch.button': 'Sign up',

    // Companies Page
    'companies.title': 'For Companies',
    'companies.subtitle': 'Strengthen your IT security with Danish freelance ethical hackers',
    'companies.howItWorks': 'How it works for you',
    'companies.step1.title': 'Set up program',
    'companies.step1.desc': 'Define what you want tested, your rules and rewards for your bug bounty program',
    'companies.step2.title': 'Danish hackers test',
    'companies.step2.desc': 'Verified ethical hackers begin testing your systems for vulnerabilities',
    'companies.step3.title': 'Receive reports',
    'companies.step3.desc': 'We verify and investigate all vulnerability reports from the hackers',
    'companies.step4.title': 'Approve & pay',
    'companies.step4.desc': 'You only pay for real and impactful vulnerabilities that are found',
    'companies.benefit1.title': 'Continuous security testing',
    'companies.benefit1.desc': 'Get your systems tested continuously by ethical hackers',
    'companies.benefit2.title': 'Cost-effective',
    'companies.benefit2.desc': 'Pay only for real vulnerabilities found - lower than consultant costs',
    'companies.benefit3.title': 'Verified ethical hackers',
    'companies.benefit3.desc': 'All ethical hackers are MitID verified and agree to our ethical guidelines',
    'companies.benefit4.title': 'Professional verification',
    'companies.benefit4.desc': 'Our own security experts verify, triage and prioritize all reported vulnerabilities',
    'companies.benefit5.title': 'Fast response',
    'companies.benefit5.desc': 'Critical vulnerabilities are reported within 24 hours',
    'companies.benefit6.title': 'Dedicated support',
    'companies.benefit6.desc': 'Danish customer service, guidance and technical support throughout the process',

    // About Page
    'about.hero.title': 'About Defend Denmark',
    'about.hero.subtitle': 'A secure digital future for Denmark through innovative cybersecurity and ethical hacking',
    'about.badge': 'About Us',
    'about.title': 'Denmark\'s First Bug Bounty Company',
    'about.subtitle': 'Pioneering cybersecurity through ethical hacking',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'We are Denmark\'s first dedicated bug bounty platform, connecting ethical hackers with Danish companies to strengthen their cybersecurity defenses. Currently in our pre-launch phase, we are building a community of skilled security researchers ready to protect Denmark\'s digital infrastructure.',
    'about.prelaunch.title': 'Pre-Launch Phase',
    'about.prelaunch.description': 'We are currently in the exciting pre-launch phase, fine-tuning our platform and building partnerships with Danish companies. We are actively onboarding both defenders and companies, please contact us if you are interested.',
    'about.hackers.title': 'Ready Security Researchers',
    'about.hackers.description': 'We have assembled a talented community of ethical hackers who are passionate about cybersecurity and ready to help Danish companies identify and fix security vulnerabilities. Our researchers undergo thorough vetting to ensure the highest standards of professionalism and integrity.',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'To become Denmark\'s leading cybersecurity platform, fostering a culture of proactive security testing and helping businesses stay ahead of cyber threats through responsible disclosure and collaborative security research.',
    'about.researchers.title': 'Meet Our Security Researchers',
    'about.researchers.subtitle': 'Talented ethical hackers ready to protect Danish companies',
    'about.researcher.mitidVerified': 'MitID Verified',
    'about.researcher.signedAgreement': 'Signed Defenders Agreement',
    'about.researcher.signedNDA': 'Signed NDA',
    'about.researcher.profession': 'Profession',
    'about.researcher.specialization': 'Specialization',
    'about.researcher.experience': 'Years of Experience',
    'about.researcher.discoveries': 'Recent Discoveries',
    'about.vulnerability.acceptedAs': 'Accepted as',
    'about.vulnerability.industry': 'Industry',
    'about.vulnerability.reward': 'Reward',
    'about.founder.quote': 'After identifying hundreds of vulnerabilities myself and working with the best Danish ethical hackers, I realized that there weren\'t many Danish companies on bug bounty platforms. This led me to launch Defend Denmark to help Danish companies work with the Danish security community to find real and impactful vulnerabilities in Danish companies',
    'about.discord.title': 'Join Our Community',
    'about.discord.description': 'Connect with fellow security researchers, stay updated on the latest programs, and participate in discussions about Danish cybersecurity.',
    'about.discord.button': 'Join us on Discord',

    // Researchers Page
    'nav.researchers': 'For Researchers',
    'researchers.badge': 'Ethical Hackers',
    'researchers.title': 'For Security Researchers',
    'researchers.subtitle': 'Get rewarded for your hacking skills',
    'researchers.howToEarn': 'How to get rewarded',
    'researchers.step1.title': 'Sign up',
    'researchers.step1.desc': 'Create profile and get verified as a defender',
    'researchers.step2.title': 'Find bugs',
    'researchers.step2.desc': 'Test selected Danish companies\' systems and find vulnerabilities',
    'researchers.step3.title': 'Report',
    'researchers.step3.desc': 'Write a detailed report about the vulnerability',
    'researchers.step4.title': 'Verification',
    'researchers.step4.desc': 'We confirm the vulnerability and assess the severity',
    'researchers.step5.title': 'Get paid',
    'researchers.step5.desc': 'Receive reward based on the vulnerability\'s criticality',
    'researchers.benefit1.title': 'High rewards',
    'researchers.benefit1.desc': 'Competitive payouts based on vulnerability criticality',
    'researchers.benefit2.title': 'Danish companies',
    'researchers.benefit2.desc': 'Work with well-known Danish brands and companies',
    'researchers.benefit3.title': 'Fast verification',
    'researchers.benefit3.desc': 'Receive feedback on found vulnerability within 5 business days',
    'researchers.benefit4.title': 'Professional support',
    'researchers.benefit4.desc': 'Get help with reporting and communication with companies',
    'researchers.benefit5.title': 'Gamification',
    'researchers.benefit5.desc': 'Receive points and recognition for all vulnerabilities, even if they don\'t give payout',
    'researchers.benefit6.title': 'Legal protection',
    'researchers.benefit6.desc': 'Safe framework for ethical hacking under Danish laws',
    'researchers.requirements.title': 'Requirements',
    'researchers.requirements.citizen': 'Danish Citizen or Resident. MitID access is required',
    'researchers.requirements.agreement': 'Willing to accept the defenders agreement',
    'researchers.requirements.record': 'Clean criminal record',
    'researchers.requirements.disclosure': 'Committed to responsible disclosure',
    'researchers.process.title': 'How It Works',
    'researchers.process.step1': 'Apply and get vetted by our security team',
    'researchers.process.step2': 'Receive access to authorized testing targets',
    'researchers.process.step3': 'Find and report vulnerabilities responsibly',
    'researchers.process.step4': 'Get rewarded for validated discoveries',
    'researchers.join.title': 'Join the Platform',
    'researchers.join.description': 'Be notified when researcher applications open',
    'researchers.join.submit': 'Get Notified',

    // Spotlight / Security Researchers Carousel
    'spotlight.title': 'Meet Our Security Researchers',
    'spotlight.subtitle': 'Talented ethical hackers ready to protect Danish companies',
    'spotlight.disclaimer': 'Note: The vulnerabilities described below are not necessarily findings in Defend Denmark\'s customers, but also, independent research or contract work, and are presented here to demonstrate the skills and expertise of ethical hackers.',
    'spotlight.mitidVerified': 'MitID Verified',
    'spotlight.agreementSigned': 'Agreement Signed',
    'spotlight.ndaSigned': 'NDA Signed',
    'spotlight.profession': 'Profession',
    'spotlight.specialization': 'Specialization',
    'spotlight.experience': 'years',
    'spotlight.discoveries': 'Recent Discoveries',
    'spotlight.reward': 'Reward:',
    'spotlight.industry': 'Industry:',
    'spotlight.cvss': 'CVSS:',
    'spotlight.acceptedAs': 'Accepted as:',

    // Fund additional keys
    'fund.howItWorks': 'How the Community Fund Works',
    'fund.flowchartDesc': 'The Community Fund creates a sustainable ecosystem where businesses contribute to cybersecurity for organizations that cannot afford it, supported by ethical hackers who help secure Denmark\'s digital infrastructure.',

    // Not Found Page
    'notFound.message': 'Oops! Page not found',
    'notFound.returnHome': 'Return to Home',

    // Common
    'common.emailPlaceholder': 'Enter your email'
  },
  da: {
    // Navigation
    'nav.companies': 'For Virksomheder',
    'nav.bugBounty': 'Bug Bounty Platform',
    'nav.communityFund': 'Fællesskabsfonden',
    'nav.about': 'Om Os',
    
    // Hero Section
    'hero.title': 'Et sikrere digitalt',
    'hero.titleAccent': 'Danmark',
    'hero.subtitle': 'Defend Denmark er den første af sin slags i Danmark. Vi samarbejder med landets førende etiske hackere, som simulerer ondsindede aktørers metoder og derved finder sikkerhedssårbarheder i virksomheder og organisationers softwaresystemer.',
    'hero.bookDemo': 'Book en Demo',
    'hero.learnMore': 'Lær Mere',
    'hero.earlyAccess': 'Få Tidlig Adgang',
    'hero.emailPlaceholder': 'Indtast din email',
    'hero.joinWaitlist': 'Tilmeld Venteliste',
    'hero.waitlistText': 'Vær den første til at vide, hvornår vi lancerer i Danmark',
    
    // Preventive Measures
    'preventive.title': 'Forebyggende foranstaltninger',
    'preventive.description': 'Vores etiske hackere simulerer rigtige angreb og finder nye sårbarheder i de IT-systemer, som vores kunder bruger, drifter eller selv bygger. Ved proaktivt at identificere disse problemer hjælper vi vores kunder med at styrke deres samlede sikkerhedsposition og reducerer risikoen for at sårbarhederne bliver udnyttet af reelle trusselsaktører.',
    
    // Bug Bounty Page
    'bugBounty.hero.title': 'Proaktiv sikkerhed',
    'bugBounty.hero.subtitle': 'Styrk jeres digitale postur med Danmarks førende etiske hackere',
    'bugBounty.hero.bookDemo': 'Book en Demo',
    'bugBounty.what.title': 'Hvad er en bug bounty platform?',
    'bugBounty.what.desc1': 'En bug bounty platform er en tjeneste, der forbinder etiske hackere med organisationer for at identificere sårbarheder i deres IT-systemer. Organisationer kan vælge hvad de ønsker at eksponere for de etiske hackere, og tilbyder belønninger (bounties) for opdagelse og rapportering af specifikke typer bugs, såsom sårbarheder i software, hjemmesider eller applikationer. De danske etiske hackere bruger deres færdigheder til at teste systemerne inden for det aftalte rammer og leverer detaljerede rapporter om de fejl som bryder sikkerheden hos organisationerne. Defend Denmark faciliterer sikker kommunikation, verificerer fund og sikrer, at betalinger foretages til de etiske hackere, som selv bidrager med information om reelle sårbarheder. Denne model hjælper organisationer med at forbedre deres cybersikkerhedspostur omkostningseffektivt ved at udnytte dette unikke netværk af eksperter.',
    'bugBounty.what.desc2': 'Defend Denmark er en unik, landsdækkende bug bounty platform, der ønsker at levere "crowdsourced" pentesting til større virksomheder, SMV\'er og statslige institutioner i Danmark. Dette gøres ved at levere en fælles platform, som forbinder de etiske hackere med disse organisationer.',
    'bugBounty.what.desc3': 'Danmark har en stor mængde af dygtige etiske hackere. I Defend Denmark finder vi dem, verificerer dem og opfordrer dem til at finde sårbarheder hos vores kunder. Alle vores etiske hackere er MitID-verificerede og har en ren straffeattest, de accepterer alle at teste etisk og udelukkende inden for de rammer som er sat af virksomheden.',
    'bugBounty.what.desc4': 'Defend Denmarks bug bounty platform er et proaktivt cybersikkerhedsinitiativ, der udnytter ekspertise og færdigheder fra etiske hackere til fordel for det digitale danmark. Denne crowdsourcede tilgang udnytter kollektive indsatser til at identificere og adressere sikkerhedssårbarheder i virksomheders systemer, før de fører til alvorlige brud, ransomware eller datalækager.',
    'bugBounty.what.desc5': 'Defend Denmarks vision er, at alle virksomheder og organisationer i Danmark skal have adgang til bug bounty platformen. På denne måde styrker vi sikkerheden af Danmarks digitale infrastruktur og øger vores digitale modstandsdygtighed.',

    // Bug Bounty Concept
    'concept.badge': 'Bug Bounty Programmer',
    'concept.title': 'Hvad er Bug Bounty?',
    'concept.subtitle': 'Bug bounty programmer er crowdsourcede intitiativer inden for cybersikkerhed, hvor organisationer inviterer etiske hackere til at finde og rapportere sikkerhedssårbarheder i bytte for belønninger. Denne samarbejdstilgang hjælper organisationer med at identificere svagheder, før de kan udnyttes af ondsindede aktører, samtidig med at der udelukkende betales for reelle sårbarheder.',
    'concept.feature1.title': 'Opdagelse af Sårbarheder',
    'concept.feature1.desc': 'De etiske hackere finder og rapporterer sårbarheder i dine systemer, før ondsindede aktører kan udnytte dem.',
    'concept.feature2.title': 'Kontinuerlig Sikkerhed',
    'concept.feature2.desc': 'I stedet for eller som supplement til årlige pentests, kan det fællesskab der er inden for etisk hacking i Danmark udnyttes. Dette skaber mulighed for kontinuerlig test af jeres systemer.',
    'concept.feature3.title': 'Samarbejde om Sårbarheder',
    'concept.feature3.desc': 'Defend Denmark og de etiske hackere, hjælper jer med at forstå jeres digitale landskab og dets sikkerhed.',
    'concept.feature4.title': 'Belønningssystem',
    'concept.feature4.desc': 'Fair kompensation ydes til de etiske hackere, der hjælper med at forbedre din sikkerhedsposition, jo værre en sårbarhed, jo større en udbetaling.',
    'concept.why.title': 'Hvorfor Vælge Bug Bounty Programmer?',
    'concept.why.benefit1': 'Mere omkostningseffektiv end traditionelle pentests, med en betal-per-sårbarhed model',
    'concept.why.benefit2': 'Adgang til divers ekspertise fra de danske etiske hackere',
    'concept.why.benefit3': 'Jeres systemer bliver kontinuerligt testet med nye øjne og færdigheder',
    'concept.why.benefit4': 'Et omdømme som en virksomhed der tager cybersikkerhed seriøst',
    'concept.why.tagline': 'En forpligtigelse til at kontinuerligt blive testet, viser jeres dedikation til at holde jeres systemer sikre.',

    // Bug Bounty Steps
    'steps.badge': 'Sådan Fungerer Det',
    'steps.title': 'Bug Bounty Proces',
    'steps.subtitle': 'Vores 8-trins tilgang sikrer grundig sikkerhedstest og ansvarlig sårbarhedshåndtering for danske organisationer.',
    'steps.1.title': 'Aktivér Elite Talent',
    'steps.1.desc': 'Vi engagerer Danmarks mest dygtige cybersikkerhedsprofessionelle til at styrke dit digitale forsvar.',
    'steps.2.title': 'Kom i gang på platformen',
    'steps.2.desc': 'Vores platformudrulning er meget lige til, og hackerne begynder øjeblikkeligt.',
    'steps.3.title': 'Simulér Rigtige Angreb',
    'steps.3.desc': 'Vores hackere simulérer de reelle trusselaktørers metoder mod dine systemer.',
    'steps.4.title': 'Validér Sårbarheder',
    'steps.4.desc': 'Vores team verificerer hver en sårbarhed, vurderer alvorlighed og sørger for at alt er dokumenteret.',
    'steps.5.title': 'Modtag handlingsrettet viden',
    'steps.5.desc': 'Modtag detaljeret teknisk dokumentation og praktisk råd om fix.',
    'steps.6.title': 'Belønning for Opdagelser',
    'steps.6.desc': 'Kompensér de etiske hackere for validerede og reelle sårbarheder. Belønningen stiger med sårbarhedens alvorlighed.',
    'steps.7.title': 'Bidrag til Fællesskabet',
    'steps.7.desc': 'En procentdel af hver belønning støtter Danmarks bredere cybersikkerhedsøkosystem - Fællesskabsfonden.',
    'steps.8.title': 'Ansvarlig Offentliggørelse',
    'steps.8.desc': 'Defend Denmark faciliterer en sikker kanal til offentliggørelse af vigtige sårbarheder, sådan skaber vi et sikrere digitalt miljø.',
    
    // Community Fund
    'fund.hero.title': 'Fællesskabsfonden',
    'fund.hero.subtitle': 'Styrker Danmarks cybersikkerhed gennem fællesskabsdrevet innovation og støtte',
    'fund.badge': 'Fællesskabseffekt',
    'fund.title': 'Fællesskabsfonden',
    'fund.subtitle': 'Cybersikkerhed for alle',
    'fund.intro.desc1': 'Vores bug bounty platform er unik ved at være drevet af fællesskabet. Med en fælles pulje, der finansieres af virksomheder, der investerer i deres egen sikkerhed, men som ved at forbedre deres egen sikkerhed også ønsker at bidrage til at beskytte Danmark. Samtidig er fonden designet til at gavne f.eks. velgørenhedsorganisationer, start-ups og offentlige institutioner med begrænsede ressourcer.',
    'fund.intro.desc2': 'Fonden er baseret på det sociale ansvar hos de organisationer og virksomheder, der har budgettet til at finansiere deres eget bug bounty program og viser vilje til at hjælpe med at finansiere et system designet til sikring af fællesskabet som helhed.',
    'fund.intro.desc3': 'Fællesskabsfonden er designet til dem, der ikke har de økonomiske midler, og er samtidig en måde at opfordre etiske hackere til at rapportere alle de sårbarheder som de kunne støde på, uanset hvem der er påvirket.',
    'fund.activate.title': 'Lad os udnytte ekspertisen',
    'fund.activate.desc1': 'Med fællesskabsfonden skaber vi et incitamentssystem, hvor den  ekspertisen fra etiske hackere udnyttes til fordel for fællesskabet. Belønninger udbetales fra fonden for fund af sårbarheder, som der rapporteres til Defend Denmark, hos virksomheder eller institutioner, der ikke har midlerne til selv at betale belønninger.',
    'fund.activate.desc2': 'Defend Denmarks fremtidige vision er, at alle virksomheder og institutioner i Danmark kan bruge bug bounty platformen til at øge deres cybersikkerhed.',
    'fund.disclosure.title': 'Ansvarlig offentliggørelse af sårbarheder',
    'fund.disclosure.desc': 'Ansvarlig offentliggørelse af sårbarheder (Responsible Vulnerability Disclosure) er et integreret koncept hos Defend Denmarks bug bounty platform. Vi fokuserer på den digitale sikkerhed for fællesskabet som helhed, ikke kun vores kunder.',
    'fund.structure.title': 'Fondens struktur',
    'fund.structure.desc1': 'Fællesskabsfonden finansieres på den ene side af Defend Denmarks kunder og på den anden side af fællesskabet af etiske hackere.',
    'fund.structure.desc2': 'Kundens bidrag er baseret på de betalte belønninger for fund af sårbarheder, oven på disse betalinger tilføjes et fladt gebyr på 10%, som er kundens bidrag til fonden, hver gang de betaler for en sårbarhed. Fællesskabsfonden vokser derfor med hver sårbarhed, der findes.',
    'fund.structure.desc3': 'Etiske hackere kan også yde frivillige bidrag til fonden fra deres egne belønninger de får udbetalt.',
    'fund.structure.desc4': 'Fondens udbetaling af belønninger er afhængig af dens status på et givent tidspunkt og de potentielle konsekvenser af den rapporterede sårbarhed for Danmarks digitale fællesskab.',
    'fund.collab.title': 'Samarbejde om  Sikkerhed',
    'fund.collab.desc': 'Virksomheder og etiske hackere bidrager sammen til at styrke Danmarks samlede cybersikkerhedspostur.',
    'fund.nonprofit.title': 'Non-Profit Support',
    'fund.nonprofit.desc': 'Fonden hjælper med at fremme ansvarlig offentliggørelse af sårbarheder hos organisationer som ikke har midlerne til selv at betale for det.',
    'fund.impact.title': 'Voksende Effekt',
    'fund.impact.desc': 'Efterhånden som flere organisationer deltager, vokser fonden til at støtte et ekspanderende netværk af digitale intitativer inden for cybersikkerhed.',
    'fund.stayInformed': 'Bliv Informeret',
    'fund.updatesText': 'Få opdateringer om fællesskabsfondets milepæle og effekthistorier.',
    'fund.emailPlaceholder': 'Din email',
    'fund.subscribe': 'Abonnér',
    'fund.fundTitle': 'Fællesskabsfond',
    'fund.fundDesc': 'Sparer midler sammen til at beskytte Danmarks digitale infrastruktur',
    'fund.companyContrib': 'Virksomhedsbidrag',
    'fund.expertContrib': 'Ekspertbidrag',
    'fund.prelaunch': 'Pre-launch fase',
    'fund.launchText': 'Fondens status vil blive vist, når Defend Denmark officielt lancerer.',
    
    // Footer
    'footer.stayConnected': 'Hold Forbindelse',
    'footer.newsletterText': 'Få opdateringer om Defend Denmarks lancering, cybersikkerhedsindsigt og fællesskabsinitiativer leveret til din indbakke.',
    'footer.emailPlaceholder': 'Indtast din email',
    'footer.subscribe': 'Abonnér',
    'footer.tagline': 'Sikrer Danmarks digitale fremtid gennem samarbejde med fælleskabet.',
    'footer.platform': 'Platform',
    'footer.bugBounty': 'Bug Bounty',
    'footer.securityTesting': 'Sikkerhedstest',
    'footer.vulnManagement': 'Sårbarhedshåndtering',
    'footer.responsibleDisclosure': 'Ansvarlig Offentliggørelse',
    'footer.community': 'Fællesskab',
    'footer.communityFund': 'Fællesskabsfonden',
    'footer.securityExperts': 'Sikkerhedseksperter',
    'footer.events': 'Begivenheder',
    'footer.resources': 'Ressourcer',
    'footer.company': 'Virksomhed',
    'footer.companyName': 'Defend Denmark ApS',
    'footer.address1': 'Reventlowsgade 18, 3. th',
    'footer.address2': '1651 København V, DK',
    'footer.email': 'info@defenddenmark.dk',
    'footer.about': 'Om os',
    'footer.forResearchers': 'For Etiske Hackere',
    'footer.forCompanies': 'For Virksomheder',
    'footer.contact': 'Kontakt',
    'footer.privacy': 'Privatlivspolitik',
    'footer.terms': 'Servicevilkår',
    'footer.copyright': '© 2025 Defend Denmark. Alle rettigheder forbeholdes.',
    'footer.sisterCompany': 'Søstervirksomhed til Defend Iceland',
    'footer.prelaunch.title': 'Bliv en del af Defend Denmark',
    'footer.prelaunch.description': 'Uanset om du er etisk hacker eller en virksomhed som ønsker at arbejde med etiske hackere, er vi ivrige efter at byde dig velkommen på platformen. Udfyld venligst formularen, så vender vi tilbage til dig hurtigst muligt.',
    'footer.prelaunch.button': 'Skriv dig op',
    
    // Companies Page
    'companies.title': 'For Virksomheder',
    'companies.subtitle': 'Styrk jeres IT-sikkerhed med danske etiske hackere',
    'companies.howItWorks': 'Sådan fungerer det for jer',
    'companies.step1.title': 'Opsæt et program',
    'companies.step1.desc': 'Definér hvad I gerne vil have testet, jeres regler og belønningsrammen for jeres bug bounty program',
    'companies.step2.title': 'Danske hackere tester',
    'companies.step2.desc': 'Verificerede danske etiske hackere begynder at teste jeres systemer for sårbarheder',
    'companies.step3.title': 'Modtag rapporter',
    'companies.step3.desc': 'Vi verificerer og godkender alle rapporter om sårbarheder fra hackerne',
    'companies.step4.title': 'Godkend & betal',
    'companies.step4.desc': 'I betaler kun for reelle og vigtige sårbarheder som bliver fundet',
    'companies.benefit1.title': 'Kontinuerlig sikkerhedstest',
    'companies.benefit1.desc': 'Få jeres systemer testet løbende af etiske hackere',
    'companies.benefit2.title': 'Omkostningseffektiv',
    'companies.benefit2.desc': 'Betal kun for reelle sårbarheder der bliver fundet - lavere konsulentomkostninger',
    'companies.benefit3.title': 'Verificerede etiske hackere',
    'companies.benefit3.desc': 'Alle etiske hackere bliver MitID verificerede og godkender reglementet for etisk hacking',
    'companies.benefit4.title': 'Professionel verificering',
    'companies.benefit4.desc': 'Vores egne sikkerhedseksperter verificerer, triagerer og prioriterer alle rapporterede sårbarheder',
    'companies.benefit5.title': 'Hurtig respons',
    'companies.benefit5.desc': 'Kritiske sårbarheder rapporteres inden for 24 timer',
    'companies.benefit6.title': 'Dedikeret support',
    'companies.benefit6.desc': 'Dansk kundeservice, vejledning og teknisk support gennem hele processen',
    
    // About Page
    'about.hero.title': 'Om Defend Denmark',
    'about.hero.subtitle': 'En sikker digital fremtid for Danmark gennem innovativ cybersikkerhed og etisk hacking',
    'about.badge': 'Om Os',
    'about.title': 'Danmarks Første Bug Bounty Virksomhed',
    'about.subtitle': 'Pionerer inden for cybersikkerhed gennem etisk hacking',
    'about.mission.title': 'Vores Mission',
    'about.mission.description': 'Vi er Danmarks første dedikerede bug bounty platform, der forbinder etiske hackere med danske virksomheder for at styrke deres cybersikkerhedsforsvar. Vi er i øjeblikket i vores pre-launch fase og ønsker at bygger et fællesskab af dygtige etiske hackere, der er klar til at beskytte Danmarks digitale infrastruktur.',
    'about.prelaunch.title': 'Pre-Launch Fase',
    'about.prelaunch.description': 'Vi er i øjeblikket i den spændende pre-launch fase, hvor vi finjusterer vores platform og bygger partnerskaber med danske virksomheder. Vi onboarder aktivt virksomheder og etiske hackere, tag endelig kontakt hvis du/i er intereseret.',
    'about.hackers.title': 'Etiske hackere står klar',
    'about.hackers.description': 'Vi har samlet et talentfuldt fællesskab af etiske hackere, der brænder for cybersikkerhed og er klar til at hjælpe danske virksomheder med at identificere og rette sårbarheder. Vores etiske hackere gennemgår grundig kontrol for at sikre de højeste standarder for professionalisme og integritet.',
    'about.vision.title': 'Vores Vision',
    'about.vision.description': 'At blive Danmarks førende cybersikkerhedsplatform, der fremmer en kultur med proaktiv sikkerhedstest og hjælper virksomheder med at være foran cybertrusler gennem ansvarlig offentliggørelse og samarbejde omkring etisk hacking.',
    'about.researchers.title': 'Mød Vores etiske hackere',
    'about.researchers.subtitle': 'Talentfulde etiske hackere klar til at beskytte danske virksomheder',
    'about.researcher.mitidVerified': 'MitID Verificeret',
    'about.researcher.signedAgreement': 'Underskrevet Defenders Aftale',
    'about.researcher.signedNDA': 'Underskrevet NDA',
    'about.researcher.profession': 'Profession',
    'about.researcher.specialization': 'Specialisering',
    'about.researcher.experience': 'Års Erfaring',
    'about.researcher.discoveries': 'Nylige Opdagelser',
    'about.vulnerability.acceptedAs': 'Accepteret som',
    'about.vulnerability.industry': 'Branche',
    'about.vulnerability.reward': 'Belønning',
    'about.founder.quote': 'Efter selv at have identificeret hundredevis af sårbarheder og arbejdet med de dygtigste danske etiske hackere, gik det op for mig at der ikke var særligt mange danske virksomheder på bug bounty platforme. Dette fik mig til at sætte Defend Denmark i verden, for at hjælpe danske virksomheder med at arbejde med den danske sikkerheds-community om at finde reelle og vigtige sårbarheder i danske virksomheder.',
    'about.discord.title': 'Bliv en del af fællesskabet',
    'about.discord.description': 'Kom i kontakt med andre etiske hackere, bliv opdateret om de nyeste programmer og deltag i diskussioner om dansk cybersikkerhed.',
    'about.discord.button': 'Join os på Discord',
    
    // Researchers Page
    'nav.researchers': 'For Etiske Hackere',
    'researchers.badge': 'Etiske Hackere',
    'researchers.title': 'For Etiske Hackere',
    'researchers.subtitle': 'Tjen penge på dine hacking skills',
    'researchers.howToEarn': 'Sådan bliver du belønnet',
    'researchers.step1.title': 'Tilmeld dig',
    'researchers.step1.desc': 'Opret profil og bliv verificeret som etisk hacker',
    'researchers.step2.title': 'Find bugs',
    'researchers.step2.desc': 'Test de udvalgte danske virksomheders systemer og find sårbarheder',
    'researchers.step3.title': 'Rapportér',
    'researchers.step3.desc': 'Skriv en detaljeret rapport om sårbarheden',
    'researchers.step4.title': 'Verifikation',
    'researchers.step4.desc': 'Vi bekræfter sårbarheden og vurderer alvorligheden',
    'researchers.step5.title': 'Bliv betalt',
    'researchers.step5.desc': 'Modtag belønning baseret på sårbarhedens kritikalitet',
    'researchers.benefit1.title': 'Høje belønninger',
    'researchers.benefit1.desc': 'Konkurrencedygtige udbetalinger baseret på sårbarhedens kritikalitet',
    'researchers.benefit2.title': 'Danske virksomheder',
    'researchers.benefit2.desc': 'Arbejd med kendte danske brands og virksomheder',
    'researchers.benefit3.title': 'Hurtig verificering',
    'researchers.benefit3.desc': 'Modtag feedback på den fundne sårbarhed inden for 5 hverdage',
    'researchers.benefit4.title': 'Professionel support',
    'researchers.benefit4.desc': 'Få hjælp til rapportering og kommunikation med virksomheder',
    'researchers.benefit5.title': 'Gamification',
    'researchers.benefit5.desc': 'Modtag point for alle sårbarheder, også selvom de ikke giver udbetaling',
    'researchers.benefit6.title': 'Legal protection',
    'researchers.benefit6.desc': 'Sikre rammer for etisk hacking under danske love',
    'researchers.requirements.title': 'Krav',
    'researchers.requirements.citizen': 'Dansk statsborger eller beboer. Adgang til MitID verificering er et krav',
    'researchers.requirements.agreement': 'Villig til at acceptere defenders aftalen',
    'researchers.requirements.record': 'Ren straffeattest',
    'researchers.requirements.disclosure': 'Forpligtet til ansvarlig offentliggørelse af sårbarheder',
    'researchers.process.title': 'Hvordan Det Fungerer',
    'researchers.process.step1': 'Ansøg og bliv godkendt af vores sikkerhedsteam',
    'researchers.process.step2': 'Modtag adgang til testmål',
    'researchers.process.step3': 'Find og rapportér sårbarheder ansvarligt',
    'researchers.process.step4': 'Bliv belønnet for validerede opdagelser',
    'researchers.join.title': 'Tilmeld Platformen',
    'researchers.join.description': 'Bliv underrettet når forskerapansøgninger åbner',
    'researchers.join.submit': 'Bliv Underrettet',
    
    // Spotlight / Security Researchers Carousel
    'spotlight.title': 'Mød Vores Etisk Hackere',
    'spotlight.subtitle': 'Talentfulde etiske hackere klar til at beskytte danske virksomheder',
    'spotlight.disclaimer': 'Bemærk: Sårbarhederne beskrevet nedenfor er ikke nødvendigvis fund i Defend Denmarks kunder, men også, uafhængig research eller kontraktarbejde, og præsenteres her for at demonstrere de etiske hackeres færdigheder og ekspertise.',
    'spotlight.mitidVerified': 'MitID Verificeret',
    'spotlight.agreementSigned': 'Aftale Underskrevet',
    'spotlight.ndaSigned': 'NDA Underskrevet',
    'spotlight.profession': 'Profession',
    'spotlight.specialization': 'Specialisering',
    'spotlight.experience': 'år',
    'spotlight.discoveries': 'Seneste Opdagelser',
    'spotlight.reward': 'Belønning:',
    'spotlight.industry': 'Branche:',
    'spotlight.cvss': 'CVSS:',
    'spotlight.acceptedAs': 'Accepteret som:',
    
    // Fund additional keys
    'fund.howItWorks': 'Sådan Fungerer Fællesskabsfonden',
    'fund.flowchartDesc': 'Fællesskabsfonden skaber et bæredygtigt økosystem, hvor virksomheder bidrager til cybersikkerhed for organisationer, der ikke selv har råd til det, støttet af etiske hackere, der hjælper med at sikre Danmarks digitale infrastruktur.',
    
    // Not Found Page
    'notFound.message': 'Ups! Siden blev ikke fundet',
    'notFound.returnHome': 'Tilbage til Forsiden',
    
    // Common
    'common.emailPlaceholder': 'Indtast din email'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('da');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};